package com.silenteight.sens.webapp.backend.reportscb;

import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Value;
import lombok.extern.slf4j.Slf4j;

import com.silenteight.sens.webapp.backend.report.Report;
import com.silenteight.sens.webapp.backend.report.ReportGenerator;
import com.silenteight.sens.webapp.backend.user.dto.UserDto;
import com.silenteight.sens.webapp.common.support.csv.CsvBuilder;
import com.silenteight.sens.webapp.common.support.csv.LinesSupplier;
import com.silenteight.sens.webapp.common.time.DateFormatter;
import com.silenteight.sens.webapp.common.time.TimeSource;

import java.util.List;
import java.util.stream.Stream;

import static com.silenteight.sens.webapp.backend.reportscb.ReportColumns.*;
import static java.util.stream.Collectors.toList;
import static java.util.stream.Stream.concat;
import static java.util.stream.Stream.of;

@Slf4j
@RequiredArgsConstructor
class AccountsReportGenerator implements ReportGenerator {

  private static final String REPORT_NAME = "accounts-report";
  private static final String FILE_NAME = REPORT_NAME + ".csv";

  @NonNull
  private final UserListRepository repository;

  @NonNull
  private final TimeSource timeSource;

  @NonNull
  private final DateFormatter timeFormatter;

  @Override
  public String getName() {
    return REPORT_NAME;
  }

  @Override
  public Report generateReport() {
    return new AccountsReport(FILE_NAME, getReportData());
  }

  private LinesSupplier getReportData() {
    List<ReportUserDto> users = getUsersDto();
    String date = timeFormatter.format(timeSource.now());
    String reportHeader = new ReportHeaderTemplate().getHeader(date, users.size());
    return () -> concat(of(reportHeader), buildReportData(users));
  }

  private List<ReportUserDto> getUsersDto() {
    return repository.list().stream().flatMap(this::getUserDto).collect(toList());
  }

  private Stream<ReportUserDto> getUserDto(UserDto user) {
    if (user.getRoles().isEmpty())
      return of(new ReportUserDto(user, "", timeFormatter));

    return user.getRoles().stream().map(role -> new ReportUserDto(user, role, timeFormatter));
  }

  private Stream<String> buildReportData(List<ReportUserDto> usersToReport) {
    return new CsvBuilder<>(usersToReport.stream())
        .cell(APPLICATION_NAME, a -> APPLICATION_NAME_VALUE)
        .cell(ACCOUNT_OWNER, ReportUserDto::getUserName)
        .cell(ACCOUNT_NAME, ReportUserDto::getUserName)
        .cell(ACCOUNT_TYPE, ReportUserDto::getAccountType)
        .cell(ACCOUNT_STATUS, ReportUserDto::getAccountStatus)
        .cell(IS_PRIVILEGED, ReportUserDto::isPrivileged)
        .cell(ACCOUNT_DESCRIPTION, ReportUserDto::getAccountDescription)
        .cell(CREATED_DATE, ReportUserDto::getCreatedAt)
        .cell(LAST_LOGIN, ReportUserDto::getLastLoginAt)
        .cell(EXPIRY_DATE, a -> "")
        .cell(ENTITLEMENT_NAME, ReportUserDto::getRole)
        .lines();
  }

  private static class ReportHeaderTemplate {

    private static final String HEADER =
        "Application Name,Surveillance Optimization,,,,,,,,,%n"
            + "Report Generated By,System,,,,,,,,,%n"
            + "Run Date,%s,,,,,,,,,%n"
            + "Number of data records,%d,,,,,,,,,%n";

    String getHeader(String date, int count) {
      return String.format(HEADER, date, count);
    }
  }

  @Value
  private static class AccountsReport implements Report {

    String reportFileName;
    LinesSupplier reportContent;
  }
}
