= HLD #19

- Reference ticket: *TBD*
- Reason: As a BO, I want translate dt.json to steps.

[plantuml,translate-dt-to-steps,svg]
-----
@startuml

actor boa as "Business Operator"

box "SERP CLI" #LightBlue
    database cli as "SERP CLI"
end box

boa -> cli : Translate dt.json to steps.json

cli -> cli : Read dt.json and transform to steps.json
note over cli
It will be almost 1:1 translation
end note

cli -> boa : Save steps.json file

@enduml
-----

.dt.json
[source,json]
{
  "metadata": {
    "exportedAt": "2019-09-16 19:39:50.574"
  },
  "modelSchema": {
    "features": [
      "apType",
      "isDeny",
      "nameAgent",
      "dateAgent",
      "nationalIdAgent",
      "passportAgent",
      "documentAgent",
      "genderAgent",
      "nationalityAgent",
      "residencyAgent"
    ]
  },
  "decisionTree": {
    "decisionTreeId": 1,
    "decisionTreeName": "migrated_from_v2_9_to_serp",
    "branches": [
      {
        "branchId": 1,
        "matchGroupId": 0,
        "solution": "FALSE_POSITIVE",
        "enabled": true,
        "featureValues": [
          "I",
          "NO",
          "HQ_NO_MATCH",
          "NO_DATA",
          "NO_DATA",
          "NO_DATA",
          "NO_DATA",
          "INCONCLUSIVE",
          "MATCH",
          "MATCH"
        ],
        "remarks": "S1"
      }
    ]
  }
}


.steps.json
[source,json]
{
  "metadata": {
    "exportedAt": "2020-04-15 10:58:53.451"
  },
  "policy": {
    "policyId": "01256804-1ce1-4d52-94d4-d1876910f272",
    "policyName": "policy-name",
    "steps": [
      {
        "solution": "SOLUTION_FALSE_POSITIVE",
        "stepId": "de1afe98-0b58-4941-9791-4e081f9b8139",
        "stepName": "branchId=1",
        "stepDescription": "This is step description",
        "stepType": "BUSINESS_LOGIC",
        "featuresLogic": [
          {
            "count": 2,
            "features": {
              "apType": [ "I" ],
              "nameAgent": [ "HQ_NO_MATCH" ]
            }
          },
          {
            "count": 2,
            "features": {
              "genderAgent": [ "NO_DATA" ],
              "dateAgent": [ "NO_DATA" ],
              "nationalIdAgent": [ "NO_DATA" ],
              "passportAgent": [ "NO_DATA" ]
            }
          }
        ]
      }
    ]
  }
}
