ifdef::context[:parent-context: {context}]
[id="managing-users-{context}"]
= Integrating with SAML Configuration
:context: integrating-saml
// CONCEPT

Using SAML 2.0 protocol SENS WebApp Auth Server provides Single Sign-On (SSO) to SENS.
SENS WebApp Auth Server is acting as Service Provider (SP) and authenticates in Identity Provider (IdP).

.Procedure

. To enable SSO in SENS you need download SAML Identity Provider Metadata in XML format from production WebSSO.
+

[NOTE]
====
For SIT or UAT WebSSO, use the corresponding Identity Provider.
====
+

. Import Identity Provider XML metadata file to SENS WebApp Auth Server.
This will create an Identity Provider instance in SENS WebApp Auth Server.
+

. Export a Service Provider XML metadata file from SENS WebApp Auth Server.
This metadata file contains cryptographic keys used for signing and encryption of SAML communication.
+

. Send exported metadata to the team responsible for WebSSO and ask them to upload it to Identity Provider.
This will result in Identity Provider trusting SENS WebApp Auth Server.
+
When the metadata will be uploaded to Identity Provider you will be able to login to SENS using SAML.


For details, see the following sections.

//========================================================================================

include::integrating-saml/importing-saml.adoc[leveloffset=+1]

include::integrating-saml/exporting-saml.adoc[leveloffset=+1]

include::integrating-saml/removing-saml.adoc[leveloffset=+1]

//========================================================================================
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
