### Get OAuth2 authorization token using client credentials flow
// @no-log
// @no-cookie-jar
POST {{authurl}}/protocol/openid-connect/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=utf-8

client_id={{client-id}}&client_secret={{client-secret}}&grant_type=client_credentials

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("access_token", response.body["access_token"]);
%}

### Adds a new version of match.ftl file to ae_comment_template table in db
POST {{baseUrl}}/rest/ae/comment/template
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

< match-template.json

### Get status no token required
GET {{baseUrl}}/rest/ae/status
Accept: application/json
Content-Type: application/json

