### Adds a new version of match.ftl file to ae_comment_template table in db
POST {{baseUrl}}/rest/ae/comment/template/add
Accept: application/json
Content-Type: application/json

< match-template.json
