# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identification_mismatch_agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="identification_mismatch_agent.proto",
    package="silenteight.agent.identification_mismatch_agent.v1.api",
    syntax="proto3",
    serialized_options=b"\n@com.silenteight.proto.agent.identification_mismatch_agent.v1.apiB#IdentificationMismatchAgentApiProtoP\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n#identification_mismatch_agent.proto\x12\x36silenteight.agent.identification_mismatch_agent.v1.api"\xa8\x01\n"CheckIdentificationMismatchRequest\x12\x16\n\x0ematching_field\x18\x01 \x01(\t\x12\x15\n\rmatching_text\x18\x02 \x01(\t\x12\x16\n\x0ewatchlist_type\x18\x03 \x01(\t\x12\x1e\n\x16watchlist_search_codes\x18\x04 \x03(\t\x12\x1b\n\x13watchlist_bic_codes\x18\x05 \x03(\t"\xa2\x01\n#CheckIdentificationMismatchResponse\x12\x10\n\x08solution\x18\x01 \x01(\t\x12i\n\x06reason\x18\x02 \x01(\x0b\x32Y.silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason"\xdb\x01\n!CheckIdentificationMismatchReason\x12\x12\n\nconclusion\x18\x01 \x01(\t\x12\x15\n\rmatching_text\x18\x02 \x01(\t\x12\x1c\n\x14raw_matched_sequence\x18\x03 \x01(\t\x12\x16\n\x0ematching_field\x18\x04 \x01(\t\x12\x15\n\rpartial_match\x18\x05 \x01(\t\x12\x16\n\x0ewatchlist_type\x18\x06 \x01(\t\x12\x14\n\x0csearch_codes\x18\x07 \x03(\t\x12\x10\n\x08\x62ic_code\x18\x08 \x01(\t2\xf8\x01\n\x1bIdentificationMismatchAgent\x12\xd8\x01\n\x1b\x43heckIdentificationMismatch\x12Z.silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest\x1a[.silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchResponse"\x00\x42i\n@com.silenteight.proto.agent.identification_mismatch_agent.v1.apiB#IdentificationMismatchAgentApiProtoP\x01\x62\x06proto3',
)


_CHECKIDENTIFICATIONMISMATCHREQUEST = _descriptor.Descriptor(
    name="CheckIdentificationMismatchRequest",
    full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="matching_field",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest.matching_field",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="matching_text",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest.matching_text",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="watchlist_type",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest.watchlist_type",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="watchlist_search_codes",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest.watchlist_search_codes",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="watchlist_bic_codes",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest.watchlist_bic_codes",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=96,
    serialized_end=264,
)


_CHECKIDENTIFICATIONMISMATCHRESPONSE = _descriptor.Descriptor(
    name="CheckIdentificationMismatchResponse",
    full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="solution",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchResponse.solution",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="reason",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchResponse.reason",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=267,
    serialized_end=429,
)


_CHECKIDENTIFICATIONMISMATCHREASON = _descriptor.Descriptor(
    name="CheckIdentificationMismatchReason",
    full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="conclusion",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.conclusion",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="matching_text",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.matching_text",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="raw_matched_sequence",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.raw_matched_sequence",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="matching_field",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.matching_field",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="partial_match",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.partial_match",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="watchlist_type",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.watchlist_type",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="search_codes",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.search_codes",
            index=6,
            number=7,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="bic_code",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason.bic_code",
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=432,
    serialized_end=651,
)

_CHECKIDENTIFICATIONMISMATCHRESPONSE.fields_by_name[
    "reason"
].message_type = _CHECKIDENTIFICATIONMISMATCHREASON
DESCRIPTOR.message_types_by_name[
    "CheckIdentificationMismatchRequest"
] = _CHECKIDENTIFICATIONMISMATCHREQUEST
DESCRIPTOR.message_types_by_name[
    "CheckIdentificationMismatchResponse"
] = _CHECKIDENTIFICATIONMISMATCHRESPONSE
DESCRIPTOR.message_types_by_name[
    "CheckIdentificationMismatchReason"
] = _CHECKIDENTIFICATIONMISMATCHREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckIdentificationMismatchRequest = _reflection.GeneratedProtocolMessageType(
    "CheckIdentificationMismatchRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHECKIDENTIFICATIONMISMATCHREQUEST,
        "__module__": "identification_mismatch_agent_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchRequest)
    },
)
_sym_db.RegisterMessage(CheckIdentificationMismatchRequest)

CheckIdentificationMismatchResponse = _reflection.GeneratedProtocolMessageType(
    "CheckIdentificationMismatchResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHECKIDENTIFICATIONMISMATCHRESPONSE,
        "__module__": "identification_mismatch_agent_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchResponse)
    },
)
_sym_db.RegisterMessage(CheckIdentificationMismatchResponse)

CheckIdentificationMismatchReason = _reflection.GeneratedProtocolMessageType(
    "CheckIdentificationMismatchReason",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHECKIDENTIFICATIONMISMATCHREASON,
        "__module__": "identification_mismatch_agent_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.agent.identification_mismatch_agent.v1.api.CheckIdentificationMismatchReason)
    },
)
_sym_db.RegisterMessage(CheckIdentificationMismatchReason)


DESCRIPTOR._options = None

_IDENTIFICATIONMISMATCHAGENT = _descriptor.ServiceDescriptor(
    name="IdentificationMismatchAgent",
    full_name="silenteight.agent.identification_mismatch_agent.v1.api.IdentificationMismatchAgent",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=654,
    serialized_end=902,
    methods=[
        _descriptor.MethodDescriptor(
            name="CheckIdentificationMismatch",
            full_name="silenteight.agent.identification_mismatch_agent.v1.api.IdentificationMismatchAgent.CheckIdentificationMismatch",
            index=0,
            containing_service=None,
            input_type=_CHECKIDENTIFICATIONMISMATCHREQUEST,
            output_type=_CHECKIDENTIFICATIONMISMATCHRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_IDENTIFICATIONMISMATCHAGENT)

DESCRIPTOR.services_by_name["IdentificationMismatchAgent"] = _IDENTIFICATIONMISMATCHAGENT

# @@protoc_insertion_point(module_scope)
