#!/bin/bash

basedir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

cd "${basedir}"

if [[ ! -d "${basedir}/node" ]] ; then
  ../gradlew npmInstall
fi

PATH="${basedir}"/node/bin:"$PATH"

exec "${basedir}"/node_modules/.bin/ng "$@"
