@Library('pipeline-shared-library') _

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: true,
    archiveArtifactsPattern: '**/build/libs/*.jar',
    includeBuildNumberInSnapshotVersion: true,
)
