@Library('pipeline-shared-library@master') _

gradleBuild(jdkVersion: 'jdk-11',
 sonarEnabled: true,
 additionalParams: [booleanParam(name: 'deployOnTest',
         description: '''Deploy on test environment in Nomad.''', defaultValue: false)],
     additionalStages: {
       stage('Deploy On Nomad Dev') {
         script {
           def utils = new com.silenteight.jenkins.ci.Utils()
           // FIXME(ahaczewski): Use `when` if possible.
           if (utils.getGitBranch() == 'master') {
             sh './nomad/deploy.sh -var-file=dev.vars'
           } else {
             echo 'This is not a release branch ignore Nomad deployment'
           }
         }
       }

       stage('Deploy On Nomad Test') {
         script {
           def utils = new com.silenteight.jenkins.ci.Utils()
           // FIXME(ahaczewski): Use `when` if possible.
           if (utils.getGitBranch() == 'master' && params.deployOnTest) {
             sh './nomad/deploy.sh -var-file=test.vars'
           } else {
             echo 'This is not a release branch ignore Nomad deployment'
           }
         }
       }
     }
 )
