from attr import dataclass

from etl_pipeline.config import pipeline_config

cn = pipeline_config.cn


EXAMPLES = [
    (
        {
            "masterId": "72951854",
            "accountSeq": "1",
            "datasetId": "1044",
            "uniqueCustomerId": "R_US_Active_Address_A05003324172_2020-01-07-07.06.28.836480\n      ",
            "masterVersion": "412740c151535f0756e8dbec7440b726c7a3e135",
            "matchId": "49159509",
            "matchStatus": "O",
            "riskScore": "-1.0",
            cn.MATCH_RECORD_VERSION_ID: "122438658",
            "matchType": "GWL",
            "entityId": "908043",
            "entityVersion": "20150505194929",
            "entity": {
                "id": "908049",
                "version": "20150505194929",
                "name": "Joe Ding",
                "listId": "15991",
                "listCode": "-1003",
                "entityType": "03",
                "createdDate": "10/16/2018",
                "lastUpdateDate": "04/19/2019",
                "source": "CON",
                "dobs": [{"dob": "MAY 6, 1981"}],
                "ids": None,
                "programs": {"program": {"type": "MSSBGWM"}},
                "sdfs": {
                    "sdf": [
                        "N/A",
                        "N/A",
                        "N/A",
                        "N/A",
                        "N/A",
                        "PLEASE CALL AML HOT LINE AT 212 762 8000 AND REF CI-079385",
                        "05/05/2015 19:49:26",
                    ]
                },
                "addresses": {
                    "address": {
                        "address1": "111 STREET 999",
                        "city": "ATLANTA",
                        "postalCode": "11111",
                        "address2": "FL;US",
                    }
                },
            },
            "entityType": "03",
            "entityTextType": "UPID",
            "sourceCode": "CON",
            "stopDescriptors": [
                {
                    "name": "Joe Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Doe",
                            "inputSynonym": "null",
                            "sdToken": "Doe",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
                {
                    "name": "Janusz Tracz Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Traczos",
                            "inputSynonym": "null",
                            "sdToken": "Traczos",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
            ],
            "firstMatchedDate": "01/08/20",
            "lastMatchedDate": "01/08/20",
            "lastReviewDate": "01/08/20",
        },
        {
            "masterId": "72951854",
            "accountSeq": "1",
            "datasetId": "1044",
            "uniqueCustomerId": "R_US_Active_Address_A05003324172_2020-01-07-07.06.28.836480\n      ",
            "masterVersion": "412740c151535f0756e8dbec7440b726c7a3e135",
            "matchId": "49159509",
            "matchStatus": "O",
            "riskScore": "-1.0",
            "inputVersionId": "122438658",
            "matchType": "GWL",
            "entityId": "908043",
            "entityVersion": "20150505194929",
            "entity": {
                "id": "908049",
                "version": "20150505194929",
                "name": "Joe Ding",
                "listId": "15991",
                "listCode": "-1003",
                "entityType": "03",
                "createdDate": "10/16/2018",
                "lastUpdateDate": "04/19/2019",
                "source": "CON",
                "dobs": [{"dob": "MAY 6, 1981"}],
                "ids": None,
                "programs": {"program": {"type": "MSSBGWM"}},
                "sdfs": {
                    "sdf": [
                        "N/A",
                        "N/A",
                        "N/A",
                        "N/A",
                        "N/A",
                        "PLEASE CALL AML HOT LINE AT 212 762 8000 AND REF CI-079385",
                        "05/05/2015 19:49:26",
                    ]
                },
                "addresses": {
                    "address": {
                        "address1": "111 STREET 999",
                        "city": "ATLANTA",
                        "postalCode": "11111",
                        "address2": "FL;US",
                    }
                },
            },
            "entityType": "03",
            "entityTextType": "UPID",
            "sourceCode": "CON",
            "stopDescriptors": [
                {
                    "name": "Joe Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Doe",
                            "inputSynonym": "null",
                            "sdToken": "Doe",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
                {
                    "name": "Janusz Tracz Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Traczos",
                            "inputSynonym": "null",
                            "sdToken": "Traczos",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
            ],
            "firstMatchedDate": "01/08/20",
            "lastMatchedDate": "01/08/20",
            "lastReviewDate": "01/08/20",
            "SRC_REF_KEY": "R_US_Active_Address_A05003324172_2020-01-07-07.06.28.836480\n      ",
            "VERSION_ID": "122438658",
            "ENTITY_ID": "908043",
            "ENTITY_VERSION": "20150505194929",
            "WL_NAME": "Joe Ding",
            "WL_DOB": ["MAY 6, 1981", ""],
            "WL_ENTITYTYPE": "03",
            "WL_COUNTRY": None,
            "WL_COUNTRY_NAME": None,
            "WL_NATIONALITY": [""],
            "WL_CITIZENSHIP": [""],
            "WL_POB": [""],
            "WL_ALIASES": [""],
            "WL_ADDRESS1": ["111 STREET 999"],
            "WL_CITY": ["ATLANTA"],
            "WL_POSTALCODE": ["11111"],
            "WL_ADDRESS2": ["FL;US"],
            "WL_MATCHED_TOKENS": r'["Doe", "Traczos"]',
            "WLP_TYPE": "I",
            "WL_DOCUMENT_NUMBER": [],
        },
    )
]


EXAMPLE_FOR_TEST_SET_REF_KEY = {
    "entityTextType": "UPIDDDD",
    "AP_TRIGGERS": {"doe": {"ALL_PARTY_NAMES": ["John, Doe Doe"]}, "johnny": {}, "sude": {}},
    "TRIGGERED_BY": [
        "entityTextType",
        "SRC_REF_KEY",
        "masterVersion",
        "entity",
        "matchStatus",
        "sourceCode",
        "matchName",
        "matchType",
        "stopDescriptors",
        "uniqueCustomerId",
    ],
    "SRC_REF_KEY": "R_RUS_Active_Address_2010-02-11-11.11",
    "masterVersion": "asd123123343124141",
    "entity": {
        "addresses": {},
        "aliases": [{"alias": "DONNY JOHN", "type": "Alias"}],
        "citizenships": [],
        "createdDate": "12/09/2010",
        "dobs": [{"dob": "01/11/1924"}],
        "entityType": "02",
        "id": "12321",
        "ids": [],
        "lastUpdateDate": "08/31/2010",
        "listCode": "EUS",
        "listId": "123",
        "name": "DOE DOE JOHN",
        "nationalities": [{"countryCode": "US", "nationality": "CHIC"}],
        "otherIds": [{"childId": "124134314"}],
        "pobs": [],
        "programs": [{"program": "UNITED STATES OF AMERICA", "type": "PPK"}],
        "sdfs": [
            {"name": "EffectiveDate", "sdf": "09/01/2010"},
            {"name": "Legal_Basis", "sdf": "2010/1209 (OJ L333)"},
            {"name": "OriginalID", "sdf": "123143414"},
        ],
        "source": "EUS",
        "titles": [{"title": "PRESIDENT OF THE ACADEMY"}],
        "version": "32131312313213",
    },
    cn.WL_MATCHED_TOKENS: '["doe", "johnny", "sude", "doe"]',
}


RESULT_FOR_EXAMPLE_FOR_TEST_SET_REF_KEY = [
    "entityTextType",
    "AP_TRIGGERS",
    "TRIGGERED_BY",
    "SRC_REF_KEY",
    "masterVersion",
    "entity",
]


EXAMPLE_PARTIES = [
    {
        "accountBU": "US_WM",
        "countryOfIncorporation": "Arabian Emirates",
        "id": "1231231231236",
        "partyCountryOfBirth": "1341412312312",
        "partyId": "1324134123123",
        "partyName": "Shaolin kung fu master",
        "taxId": "1231413412312",
        "taxIdType": "AUS",
    },
    {
        "accountBU": "US_VM_SS",
        "dobDate": "10/10/1969",
        "id": "43134134123123",
        "partyCountryOfBirth": "13413401280",
        "partyId": "31231241234124",
        "partyName": "John, Doe Doe",
        "partyPrimaryCitizenshipCountry": "Arabian Emirates",
        "taxId": "12097381208937",
        "taxIdType": "SSH",
    },
]

EXAMPLE_PARTIES_WITH_NAMES = [
    {
        "accountBU": "US_WM",
        "countryOfIncorporation": "Arabian Emirates",
        "id": "1231231231236",
        "partyCountryOfBirth": "1341412312312",
        "partyId": "1324134123123",
        "partyName": "Shaolin kung fu master",
        "taxId": "1231413412312",
        "taxIdType": "AUS",
        "partyFirstName": "Ultra",
        "partyMiddleName": "Giga",
        "partyLastName": "Pole",
    },
    {
        "accountBU": "US_VM_SS",
        "dobDate": "10/10/1969",
        "id": "43134134123123",
        "partyCountryOfBirth": "13413401280",
        "partyId": "31231241234124",
        "partyName": "John, Doe Doe",
        "partyPrimaryCitizenshipCountry": "Arabian Emirates",
        "taxId": "12097381208937",
        "taxIdType": "SSH",
    },
]


EXAMPLES_WITH_INVALID_OUTPUT = [
    (
        {
            "masterId": "72951854",
            "accountSeq": "1",
            "datasetId": "1044",
            "uniqueCustomerId": "R_US_Active_Address_A05003324172_2020-01-07-07.06.28.836480\n      ",
            "masterVersion": "412740c151535f0756e8dbec7440b726c7a3e135",
            "matchId": "49159509",
            "matchStatus": "O",
            "riskScore": "-1.0",
            cn.MATCH_RECORD_VERSION_ID: "122438658",
            "matchType": "GWL",
            "entityId": "908043",
            "entityVersion": "20150505194929",
            "entity": {
                "id": "908049",
                "version": "20150505194929",
                "name": "Joe Ding",
                "listId": "15991",
                "listCode": "-1003",
                "entityType": "03",
                "createdDate": [],
                "source": "CON",
                "dobs": [{"dob": "MAY 6, 1981"}],
                "ids": None,
                "programs": {"program": "j"},
                "sdfs": "any",
                "addresses": "dummy text",
            },
            "entityType": "03",
            "entityTextType": "UPID",
            "sourceCode": "CON",
            "stopDescriptors": [
                {
                    "name": "Joe Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Doe",
                            "inputSynonym": "null",
                            "sdToken": "Doe",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
                {
                    "name": "Janusz Tracz Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Traczos",
                            "inputSynonym": "null",
                            "sdToken": "Traczos",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
            ],
            "firstMatchedDate": "01/08/20",
            "lastMatchedDate": "01/08/20",
            "lastReviewDate": "01/08/20",
        },
        {
            "masterId": "72951854",
            "accountSeq": "1",
            "datasetId": "1044",
            "uniqueCustomerId": "R_US_Active_Address_A05003324172_2020-01-07-07.06.28.836480\n      ",
            "masterVersion": "412740c151535f0756e8dbec7440b726c7a3e135",
            "matchId": "49159509",
            "matchStatus": "O",
            "riskScore": "-1.0",
            "inputVersionId": "122438658",
            "matchType": "GWL",
            "entityId": "908043",
            "entityVersion": "20150505194929",
            "entity": {
                "id": "908049",
                "version": "20150505194929",
                "name": "Joe Ding",
                "listId": "15991",
                "listCode": "-1003",
                "entityType": "03",
                "createdDate": [],
                "source": "CON",
                "dobs": [{"dob": "MAY 6, 1981"}],
                "ids": None,
                "programs": {"program": "j"},
                "sdfs": "any",
                "addresses": "dummy text",
            },
            "entityType": "03",
            "entityTextType": "UPID",
            "sourceCode": "CON",
            "stopDescriptors": [
                {
                    "name": "Joe Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Doe",
                            "inputSynonym": "null",
                            "sdToken": "Doe",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
                {
                    "name": "Janusz Tracz Doe",
                    "totalMatchScore": "0.9230769230769231",
                    "stopDescriptorDetails": [
                        {
                            "inputToken": "Traczos",
                            "inputSynonym": "null",
                            "sdToken": "Traczos",
                            "matchScore": "0.8571428571428572",
                        }
                    ],
                },
            ],
            "firstMatchedDate": "01/08/20",
            "lastMatchedDate": "01/08/20",
            "lastReviewDate": "01/08/20",
            "SRC_REF_KEY": "R_US_Active_Address_A05003324172_2020-01-07-07.06.28.836480\n      ",
            "VERSION_ID": "122438658",
            "ENTITY_ID": "908043",
            "ENTITY_VERSION": "20150505194929",
            "WL_NAME": "Joe Ding",
            "WL_DOB": ["MAY 6, 1981", ""],
            "WL_ENTITYTYPE": "03",
            "WL_COUNTRY": None,
            "WL_COUNTRY_NAME": None,
            "WL_NATIONALITY": [""],
            "WL_CITIZENSHIP": [""],
            "WL_POB": [""],
            "WL_ALIASES": [""],
            "WL_MATCHED_TOKENS": r'["Doe", "Traczos"]',
            "WLP_TYPE": "I",
            "WL_DOCUMENT_NUMBER": [],
        },
    )
]


@dataclass
class TestAgentInput:
    agent_name: str
    payload: dict
    expected_result: dict


TEST_AGENT_INPUT_CASES = [
    TestAgentInput(
        agent_name="dob_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.dobDate": "02/31/1900",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.dobDate": "04/31/1910",
            "watchlistParty.matchRecords[0].entity.dobs[0].dob": "MAY 6, 1981",
        },
        expected_result={
            ("ap", "ALL_CONNECTED_PARTY_DOBS"): ["02/31/1900", "04/31/1910"],
            ("wl", "watchlistParty.matchRecords.WL_DOB"): ["MAY 6, 1981", ""],
        },
    ),
    TestAgentInput(
        agent_name="document_number_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.taxId": "154421273",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.taxId": "022368917",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyGovtIdNumber": "123",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyGovtIdNumber": "321",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "PARTY1_GOVTID1_NUMBER",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "131313",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "PARTY1_GOVTID2_NUMBER",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "2323232",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "1",
            "watchlistParty.matchRecords[0].entity.dobs[0].dob": "MAY 6, 1981",
            "watchlistParty.matchRecords[0].entity.ids.id": "abc123",
        },
        expected_result={
            ("ap", "ALL_CONNECTED_TAX_IDS"): ["154421273", "022368917"],
            ("ap", "ALL_CONNECTED_GOVT_IDS"): ["123", "321"],
            ("ap", "ALL_PARTY1_GOVTID1_NUMBER"): "131313",
            ("ap", "ALL_PARTY1_GOVTID2_NUMBER"): "2323232",
            ("wl", "watchlistParty.matchRecords.WL_DOCUMENT_NUMBER"): ["abc123"],
        },
    ),
    TestAgentInput(
        agent_name="company_name_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyName": "Joe Small",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyFirstName": "Joe",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyMiddleName": "Middle",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyLastName": "Small",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyName": "Johny B. Good",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyFirstName": "Johnathanno",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyMiddleName": "Budger",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyLastName": "Good",
            "alertedParty.supplementalInfo.relatedAccounts.accounts[0].fields.lastName": "Vutin",
            "alertedParty.supplementalInfo.relatedAccounts.accounts[0].fields.firstName": "Pladimir",
            "alertedParty.supplementalInfo.relatedAccounts.accounts[0].fields.beneficiaryName": "BenePladimir Vutin",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "CONCAT_NAME",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "Soft Ltd.",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "PARTY1_NAME_FULL",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "Janusz",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "22",
            "watchlistParty.matchRecords[0].entity.name": "Joe Ding",
        },
        expected_result={
            ("ap", "ALL_CONCAT_NAMES"): "Soft Ltd.",
            ("ap", "ALL_CONNECTED_PARTY_NAMES"): ["Joe Small", "Johny B. Good"],
            ("ap", "ALL_CONNECTED_PARTIES_NAMES"): [
                "Joe Middle Small",
                "Johnathanno Budger Good",
            ],
            ("ap", "ALL_CONNECTED_ACCOUNT_NAMES"): ["Pladimir Vutin"],
            ("ap", "ALL_CONNECTED_ACCOUNT_BENEFICIARY_NAMES"): ["BenePladimir Vutin"],
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_FULL",
            ): "Janusz",
            ("wl", "watchlistParty.matchRecords.WL_NAME"): "Joe Ding",
        },
    ),
    TestAgentInput(
        agent_name="name_agent_example",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyName": "Joe Small",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyFirstName": "Joe",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyMiddleName": "Middle",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyLastName": "Small",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyName": "Johny B. Good",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyFirstName": "Johnathanno",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyMiddleName": "Budger",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyLastName": "Good",
            "alertedParty.supplementalInfo.relatedAccounts.accounts[0].fields.lastName": "Vutin",
            "alertedParty.supplementalInfo.relatedAccounts.accounts[0].fields.firstName": "Pladimir",
            "alertedParty.supplementalInfo.relatedAccounts.accounts[0].fields.beneficiaryName": "BenePladimir Vutin",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "CONCAT_NAME",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "Soft Ltd.",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "PARTY1_NAME_FULL",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "Janusz",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "22",
            "watchlistParty.matchRecords[0].entity.name": "Joe Ding",
        },
        expected_result={
            ("ap", "ALL_CONCAT_NAMES"): "Soft Ltd.",
            ("ap", "ALL_CONNECTED_PARTY_NAMES"): ["Joe Small", "Johny B. Good"],
            ("ap", "ALL_CONNECTED_PARTIES_NAMES"): [
                "Joe Middle Small",
                "Johnathanno Budger Good",
            ],
            ("ap", "ALL_CONNECTED_ACCOUNT_NAMES"): ["Pladimir Vutin"],
            ("ap", "ALL_CONNECTED_ACCOUNT_BENEFICIARY_NAMES"): ["BenePladimir Vutin"],
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_FULL",
            ): "Janusz",
            ("wl", "watchlistParty.matchRecords.WL_NAME"): "Joe Ding",
        },
    ),
    TestAgentInput(
        agent_name="employer_name_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "PARTY1_EMPLOYER",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "Macro Soft Ltd.",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "PARTY1_ORGANIZATION_NAME",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "JanuszSoft Ltd.",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "22",
            "watchlistParty.matchRecords[0].entity.name": "Joe Joe Bring Ding",
            "watchlistParty.matchRecords[0].entity.aliases[0].alias": "Billabong the King",
        },
        expected_result={
            ("ap", "ALL_PARTY1_EMPLOYERS"): "Macro Soft Ltd.",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_EMPLOYER",
            ): "Macro Soft Ltd.",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_ORGANIZATION_NAME",
            ): "JanuszSoft Ltd.",
            ("wl", "watchlistParty.matchRecords.WL_NAME"): "Joe Joe Bring Ding",
            ("wl", "watchlistParty.matchRecords.WL_ALIASES"): [["Billabong the King"]],
        },
    ),
    TestAgentInput(
        agent_name="nationality_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyCountryOfBirth": "Norway",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyResidenceCountryCode": "NO",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.COUNTRY_OF_INCORPORATION": "TOGO",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyResidenceCountry": "Curacao",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyPrimaryCitizenshipCountry": "Belize",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyCountryOfBirth": "Sweden",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyResidenceCountryCode": "SE",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyResidenceCountry": "Guatemala",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyPrimaryCitizenshipCountry": "Honduras",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "ADDRESS1_COUNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "UNITED STATES OF AMERICA",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "20",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "COUNTRY1_CITIZENSHIP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "Moominland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].name": "COUNTRY_DOMICILE1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].value": "Lapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].name": "PRTY_RSDNC_CNTRY_CD",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].value": "Finland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].sortOrder": "1",
            "watchlistParty.matchRecords[0].entity.addresses[0].countryName": "United States of America",
            "watchlistParty.matchRecords[0].entity.addresses[0].country": "US",
            "watchlistParty.matchRecords[0].entity.nationalities.nationality": "American",
            "watchlistParty.matchRecords[0].entity.pobs[0].pob": "Orlando, Florida",
            "watchlistParty.matchRecords[0].entity.citizenships.citizenship": "AMMMerican",
        },
        expected_result={
            ("ap", "ALL_PARTY1_COUNTRY1_CITIZENSHIP"): "Moominland",
            ("ap", "ALL_PARTY1_COUNTRY_DOMICILE1"): "Lapland",
            ("ap", "ALL_PRTY_RSDNC_CNTRY_CD"): "Finland",
            ("ap", "ALL_PARTY1_ADDRESS1_COUNTRY"): "UNITED STATES OF AMERICA",
            ("ap", "ALL_CONNECTED_PARTY_BIRTH_COUNTRIES"): ["Norway", "Sweden"],
            ("ap", "ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES"): ["Belize", "Honduras"],
            ("ap", "ALL_CONNECTED_PARTY_RESIDENCY_COUNTRIES"): ["NO", "SE"],
            ("ap", "ALL_CONNECTED_COUNTRY_OF_INCORPORATION"): ["TOGO"],
            ("wl", "watchlistParty.matchRecords.WL_NATIONALITY"): ["American"],
            ("wl", "watchlistParty.matchRecords.WL_POB"): [["Orlando, Florida"]],
            ("wl", "watchlistParty.matchRecords.WL_CITIZENSHIP"): ["AMMMerican"],
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY"): "US",
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY_NAME"): "United States of America",
        },
    ),
    TestAgentInput(
        agent_name="party_type_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyType": "human",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyType": "monkey",
            "watchlistParty.matchRecords[0].entityType": "03",
        },
        expected_result={
            ("ap", "ALL_CONNECTED_PARTY_TYPES"): ["human", "monkey"],
            ("wl", "watchlistParty.matchRecords.WLP_TYPE"): "I",
        },
    ),
    TestAgentInput(
        agent_name="pob_agent_example",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyCountryOfBirth": "Mongolia",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.COUNTRY_OF_INCORPORATION": "TOGO",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyPrimaryCitizenshipCountry": "Belize",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyCountryOfBirth": "Kazachstan",
            "watchlistParty.matchRecords[0].entity.addresses[0].countryName": "United States of America",
            "watchlistParty.matchRecords[0].entity.addresses[0].country": "US",
            "watchlistParty.matchRecords[0].entity.pobs[0].pob": "Orlando, Florida",
            "watchlistParty.matchRecords[0].entity.nationalities.nationality": "American",
        },
        expected_result={
            ("ap", "ALL_CONNECTED_PARTY_BIRTH_COUNTRIES"): ["Mongolia", "Kazachstan"],
            ("ap", "ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES"): ["Belize"],
            ("ap", "ALL_CONNECTED_COUNTRY_OF_INCORPORATION"): ["TOGO"],
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY"): "US",
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY_NAME"): "United States of America",
            ("wl", "watchlistParty.matchRecords.WL_POB"): [["Orlando, Florida"]],
            ("wl", "watchlistParty.matchRecords.WL_NATIONALITY"): ["American"],
        },
    ),
    TestAgentInput(
        agent_name="sanctioned_country_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyCountryOfBirth": "Mongolia-1",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyPrimaryCitizenshipCountry": "Mongolia-2",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.COUNTRY_OF_INCORPORATION": "Mongolia-3",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyCountryOfBirth": "Kazachstan-1",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyPrimaryCitizenshipCountry": "Kazachstan-2",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.COUNTRY_OF_INCORPORATION": "Kazachstan-3",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "ADDRESS1_COUNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "UNITED STATES OF AMERICA",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "20",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "COUNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "UNITED STATES OF AMERICAA",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "20",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].name": "COUNTRY1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].value": "UNITED STATES OF AMERICAAA",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].sortOrder": "20",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].name": "COUNTRY1_CITIZENSHIP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].value": "Moominland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].name": "COUNTRY2_CITIZENSHIP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].value": "Goominland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].name": "COUNTRY_DOMICILE1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].value": "Lapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].name": "COUNTRY_FORMATION1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].value": "Gapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].name": "COUNTRY_OF_INCORPORATION",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].value": "Hapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].name": "PRTY_PRIM_CTZNSH_CNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].value": "Trapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].sortOrder": "1",
            "watchlistParty.matchRecords[0].entity.addresses[0].countryName": "United States of America",
            "watchlistParty.matchRecords[0].entity.addresses[0].country": "US",
            "watchlistParty.matchRecords[0].entity.name": "Ding Dong",
        },
        expected_result={
            ("ap", "ALL_CONNECTED_PARTY_BIRTH_COUNTRIES"): ["Mongolia-1", "Kazachstan-1"],
            ("ap", "ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES"): [
                "Mongolia-2",
                "Kazachstan-2",
            ],
            ("ap", "ALL_CONNECTED_COUNTRY_OF_INCORPORATION"): ["Mongolia-3", "Kazachstan-3"],
            ("ap", "ALL_PARTY1_ADDRESS1_COUNTRY"): "UNITED STATES OF AMERICA",
            ("ap", "ALL_PARTY1_COUNTRY"): "UNITED STATES OF AMERICAA",
            ("ap", "ALL_PARTY1_COUNTRY1"): "UNITED STATES OF AMERICAAA",
            ("ap", "ALL_PARTY1_COUNTRY1_CITIZENSHIP"): "Moominland",
            ("ap", "ALL_PARTY1_COUNTRY2_CITIZENSHIP"): "Goominland",
            ("ap", "ALL_PARTY1_COUNTRY_DOMICILE1"): "Lapland",
            ("ap", "ALL_PARTY1_COUNTRY_FORMATION1"): "Gapland",
            ("ap", "ALL_PARTY1_COUNTRY_OF_INCORPORATION"): "Hapland",
            ("ap", "ALL_PRTY_PRIM_CTZNSH_CNTRY"): "Trapland",
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY"): "US",
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY_NAME"): "United States of America",
            ("wl", "watchlistParty.matchRecords.WL_NAME"): "Ding Dong",
        },
    ),
    TestAgentInput(
        agent_name="residency_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyCountryOfBirth": "Norway",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.partyPrimaryCitizenshipCountry": "Belize",
            "alertedParty.supplementalInfo.relatedParties.party[0].fields.COUNTRY_OF_INCORPORATION": "TOGO",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyCountryOfBirth": "Sweden",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.partyPrimaryCitizenshipCountry": "Honduras",
            "alertedParty.supplementalInfo.relatedParties.party[1].fields.COUNTRY_OF_INCORPORATION": "GOTO",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "ADDRESS1_COUNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "5th Avenue 22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "COUNTRY_DOMICILE1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "Lapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].name": "PRTY_PRIM_CTZNSH_CNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].value": "Trapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].name": "COUNTRY2_CITIZENSHIP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].value": "Goominland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].name": "PRTY_RSDNC_CNTRY_CD",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].value": "Finland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].name": "PARTY1_COUNTRY_PEP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].value": "PEP Republic",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].sortOrder": "1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].name": "COUNTRY_OF_INCORPORATION",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].isScreenable": "false",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].value": "Hapland",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].sortOrder": "1",
            "watchlistParty.matchRecords[0].entity.addresses[0].countryName": "United States of Antarctica",
            "watchlistParty.matchRecords[0].entity.addresses[0].country": "USAntarctica",
        },
        expected_result={
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.ADDRESS1_COUNTRY",
            ): "5th Avenue 22",
            ("ap", "ALL_PARTY1_COUNTRY_DOMICILE1"): "Lapland",
            ("ap", "ALL_CONNECTED_PARTY_BIRTH_COUNTRIES"): ["Norway", "Sweden"],
            ("ap", "ALL_CONNECTED_PARTY_CITIZENSHIP_COUNTRIES"): ["Belize", "Honduras"],
            ("ap", "ALL_CONNECTED_COUNTRY_OF_INCORPORATION"): ["TOGO", "GOTO"],
            ("ap", "ALL_PRTY_PRIM_CTZNSH_CNTRY"): "Trapland",
            ("ap", "ALL_PARTY1_COUNTRY2_CITIZENSHIP"): "Goominland",
            ("ap", "ALL_PRTY_RSDNC_CNTRY_CD"): "Finland",
            ("ap", "ALL_PARTY1_COUNTRY_PEP"): "PEP Republic",
            ("ap", "ALL_PARTY1_COUNTRY_OF_INCORPORATION"): "Hapland",
            ("wl", "watchlistParty.matchRecords.WL_COUNTRY"): "USAntarctica",
            (
                "wl",
                "watchlistParty.matchRecords.WL_COUNTRY_NAME",
            ): "United States of Antarctica",
        },
    ),
    TestAgentInput(
        agent_name="hit_type_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "CONCAT_NAME",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "Joe King 0",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].name": "PARTY1_NAME_ALIAS1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].value": "Joe King 1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[1].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].name": "PARTY1_NAME_ALIAS2",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].value": "Joe King 2",
            "alertedParty.inputRecordHist.inputRecords[0].fields[2].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].name": "PARTY1_NAME_ALIAS3",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].value": "Joe King 3",
            "alertedParty.inputRecordHist.inputRecords[0].fields[3].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].name": "PARTY1_NAME_ALIAS4",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].value": "Joe King 4",
            "alertedParty.inputRecordHist.inputRecords[0].fields[4].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].name": "PARTY1_NAME_FULL",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].value": "Joe King 5",
            "alertedParty.inputRecordHist.inputRecords[0].fields[5].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].name": "ADDRESS1_COUNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].value": "Joe King 6",
            "alertedParty.inputRecordHist.inputRecords[0].fields[6].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].name": "PARTY1_COUNTRY_DOMICILE1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].value": "Joe King 7",
            "alertedParty.inputRecordHist.inputRecords[0].fields[7].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].name": "PARTY1_COUNTRY_FORMATION1",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].value": "Joe King 8",
            "alertedParty.inputRecordHist.inputRecords[0].fields[8].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[9].name": "PRTY_PRIM_CTZNSH_CNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[9].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[9].value": "Joe King 9",
            "alertedParty.inputRecordHist.inputRecords[0].fields[9].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[10].name": "PARTY1_COUNTRY2_CITIZENSHIP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[10].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[10].value": "Joe King 10",
            "alertedParty.inputRecordHist.inputRecords[0].fields[10].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[11].name": "PRTY_RSDNC_CNTRY_CD",
            "alertedParty.inputRecordHist.inputRecords[0].fields[11].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[11].value": "Joe King 11",
            "alertedParty.inputRecordHist.inputRecords[0].fields[11].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[12].name": "PARTY1_COUNTRY_DOMICILE1_REPEATED",
            "alertedParty.inputRecordHist.inputRecords[0].fields[12].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[12].value": "Joe King 12",
            "alertedParty.inputRecordHist.inputRecords[0].fields[12].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[13].name": "PARTY1_COUNTRY_PEP",
            "alertedParty.inputRecordHist.inputRecords[0].fields[13].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[13].value": "Joe King 13",
            "alertedParty.inputRecordHist.inputRecords[0].fields[13].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[14].name": "PARTY1_COUNTRY_OF_INCORPORATION",
            "alertedParty.inputRecordHist.inputRecords[0].fields[14].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[14].value": "Joe King 14",
            "alertedParty.inputRecordHist.inputRecords[0].fields[14].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[15].name": "PARTY1_ADDRESS1_COUNTRY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[15].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[15].value": "Joe King 15",
            "alertedParty.inputRecordHist.inputRecords[0].fields[15].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[16].name": "PARTY1_EMPLOYER",
            "alertedParty.inputRecordHist.inputRecords[0].fields[16].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[16].value": "Joe King 16",
            "alertedParty.inputRecordHist.inputRecords[0].fields[16].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[17].name": "PARTY1_ORGANIZATION_NAME",
            "alertedParty.inputRecordHist.inputRecords[0].fields[17].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[17].value": "Joe King 17",
            "alertedParty.inputRecordHist.inputRecords[0].fields[17].sortOrder": "22",
            "alertedParty.inputRecordHist.inputRecords[0].fields[18].name": "PARTY1_POSITION_TITLE",
            "alertedParty.inputRecordHist.inputRecords[0].fields[18].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[18].value": "Joe King 18",
            "alertedParty.inputRecordHist.inputRecords[0].fields[18].sortOrder": "22",
        },
        expected_result={
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.CONCAT_NAME",
            ): "Joe King 0",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_ALIAS1",
            ): "Joe King 1",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_ALIAS2",
            ): "Joe King 2",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_ALIAS3",
            ): "Joe King 3",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_ALIAS4",
            ): "Joe King 4",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_FULL",
            ): "Joe King 5",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.ADDRESS1_COUNTRY",
            ): "Joe King 6",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_COUNTRY_DOMICILE1",
            ): "Joe King 7",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_COUNTRY_FORMATION1",
            ): "Joe King 8",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PRTY_PRIM_CTZNSH_CNTRY",
            ): "Joe King 9",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_COUNTRY2_CITIZENSHIP",
            ): "Joe King 10",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PRTY_RSDNC_CNTRY_CD",
            ): "Joe King 11",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_COUNTRY_PEP",
            ): "Joe King 13",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_COUNTRY_OF_INCORPORATION",
            ): "Joe King 14",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_ADDRESS1_COUNTRY",
            ): "Joe King 15",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_EMPLOYER",
            ): "Joe King 16",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_ORGANIZATION_NAME",
            ): "Joe King 17",
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_POSITION_TITLE",
            ): "Joe King 18",
        },
    ),
    TestAgentInput(
        agent_name="matched_tokens_tp_marked_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "watchlistParty.matchRecords[0].stopDescriptors[0].stopDescriptorDetails[0].inputToken": "Broken Token",
        },
        expected_result={
            ("wl", "watchlistParty.matchRecords.WL_MATCHED_TOKENS"): '["Broken Token"]',
        },
    ),
    TestAgentInput(
        agent_name="ap_name_tp_marked_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "PARTY1_NAME_FULL",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "Janusz",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "22",
        },
        expected_result={
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_NAME_FULL",
            ): "Janusz",
        },
    ),
    TestAgentInput(
        agent_name="ap_id_tp_marked_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "PARTY1_ID",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "ID312",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "22",
        },
        expected_result={
            ("ap", "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.PARTY1_ID"): "ID312",
        },
    ),
    TestAgentInput(
        agent_name="ap_id_tp_marked_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "UNIQUE_KEY",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "1234321",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "22",
        },
        expected_result={
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.UNIQUE_KEY",
            ): "1234321",
        },
    ),
    TestAgentInput(
        agent_name="ap_id_tp_marked_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].name": "ACCOUNTNUMBER",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].isScreenable": "true",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].value": "191919",
            "alertedParty.inputRecordHist.inputRecords[0].fields[0].sortOrder": "22",
        },
        expected_result={
            (
                "ap",
                "alertedParty.inputRecordHist.inputRecords.INPUT_FIELD.ACCOUNTNUMBER",
            ): "191919",
        },
    ),
    TestAgentInput(
        agent_name="is_entity_match_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "watchlistParty.matchRecords[0].entityType": "00",
        },
        expected_result={
            ("ap", "AP_PARTY_TYPE"): "C",
            ("wl", "watchlistParty.matchRecords.WLP_TYPE"): "C",
        },
    ),
    TestAgentInput(
        agent_name="is_entity_match_agent",
        payload={
            "alertedParty.headerInfo.datasetName": "R_US_Active_Address",
            "alertedParty.inputRecordHist.inputRecords[0].versionId": "122438658",
            "watchlistParty.matchRecords[0].inputVersionId": "122438658",
            "watchlistParty.matchRecords[0].entityType": "03",
        },
        expected_result={
            ("ap", "AP_PARTY_TYPE"): "C",
            ("wl", "watchlistParty.matchRecords.WLP_TYPE"): "I",
        },
    ),
]
