= HLD #13

- Reference ticket: *https://silent-eight.aha.io/features/PROD-30*
- Reason: As a user of WebApp, I can see a notification related to actions I am interested in.

[plantuml,bo-gets-list-of-discrepant-branches,svg]
-----
@startuml
header Create a new notification

box "WebApp Frontend" #MintCream
    participant Frontend as "Frontend"
end box

box "Notification Service" #LightGreen
    participant Backend as "Backend"
    database db as "DB"
end box

box "Client service" #LightBlue
    participant S as "Service" order 5
end box

== Subscribe to notifications ==
Frontend -> Backend : Subscribe

note over Backend, Frontend
    * username
end note

Backend -> db : store subscriber


== Create a notification ==

S -> Backend : Create Notification
note over S, Backend
    * event type
    * parameters
    * audience
end note
Backend -> db : store a notification

Backend <-> db : set a list of subscribers

Backend -> Frontend : Push a notification via websocket
note over Backend, Frontend
    * event type
    * parameters

    Only if target user has an active subscription,
    otherwise the notification is not sent
end note


== Details notification list ==

Frontend -> Backend : Get Last Notifications
note over Backend, Frontend
    * username
    * since date
end note


Backend <-> db : check past events

Backend -> Frontend : Notification list
note over Backend, Frontend
    * created at
    * event id
    * event type
    * parameters
end note


== Unsubscribe from notifications ==

Frontend -> Backend : Unsubscribe
Backend -> db : remove from subscriber list


@enduml
-----

Notes:

- Notification service pushes notifications via websocket only if (at the time of the notification creation)
target users are subscribed. If, for whatever reason, the webagent does not receive the notification
(e.g. due to network issue), notification service does attempt any retries.
Reason: simplify the design

- There is no acknowledgment of a notification delivery. Therefore, it is impossible to determine
on the server side whether the notitfication has been delivered/ displayed by webagent or not.
Reason: simplify the design

- It is responsibility of the calling service to determine the correct moment to call
Create Notification. If there are multiple services involved in the business process, a single service
should take a role of an orchestrator (encapsulate the business rules).
Reason: Notification service, being a technical component, should not encapsulate business rules.
