# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="common.proto",
    package="silenteight.learningstore.historicaldecision.v2.api",
    syntax="proto3",
    serialized_options=b"\n=com.silenteight.proto.learningstore.historicaldecision.v2.apiB%HistoricalDecisionLearningCommonProtoP\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0c\x63ommon.proto\x12\x33silenteight.learningstore.historicaldecision.v2.api\x1a\x1fgoogle/api/field_behavior.proto"/\n\tWatchlist\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x11\n\x04type\x18\x02 \x01(\tB\x03\xe0\x41\x02"H\n\x08\x44\x65\x63ision\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x12\n\x05value\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\ncreated_at\x18\x03 \x01(\x03\x42\x03\xe0\x41\x02"#\n\rDiscriminator\x12\x12\n\x05value\x18\x01 \x01(\tB\x03\xe0\x41\x02\x42h\n=com.silenteight.proto.learningstore.historicaldecision.v2.apiB%HistoricalDecisionLearningCommonProtoP\x01\x62\x06proto3',
    dependencies=[
        google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,
    ],
)


_WATCHLIST = _descriptor.Descriptor(
    name="Watchlist",
    full_name="silenteight.learningstore.historicaldecision.v2.api.Watchlist",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Watchlist.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="type",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Watchlist.type",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=102,
    serialized_end=149,
)


_DECISION = _descriptor.Descriptor(
    name="Decision",
    full_name="silenteight.learningstore.historicaldecision.v2.api.Decision",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Decision.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Decision.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="created_at",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Decision.created_at",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=151,
    serialized_end=223,
)


_DISCRIMINATOR = _descriptor.Descriptor(
    name="Discriminator",
    full_name="silenteight.learningstore.historicaldecision.v2.api.Discriminator",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="value",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Discriminator.value",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=225,
    serialized_end=260,
)

DESCRIPTOR.message_types_by_name["Watchlist"] = _WATCHLIST
DESCRIPTOR.message_types_by_name["Decision"] = _DECISION
DESCRIPTOR.message_types_by_name["Discriminator"] = _DISCRIMINATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Watchlist = _reflection.GeneratedProtocolMessageType(
    "Watchlist",
    (_message.Message,),
    {
        "DESCRIPTOR": _WATCHLIST,
        "__module__": "common_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.learningstore.historicaldecision.v2.api.Watchlist)
    },
)
_sym_db.RegisterMessage(Watchlist)

Decision = _reflection.GeneratedProtocolMessageType(
    "Decision",
    (_message.Message,),
    {
        "DESCRIPTOR": _DECISION,
        "__module__": "common_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.learningstore.historicaldecision.v2.api.Decision)
    },
)
_sym_db.RegisterMessage(Decision)

Discriminator = _reflection.GeneratedProtocolMessageType(
    "Discriminator",
    (_message.Message,),
    {
        "DESCRIPTOR": _DISCRIMINATOR,
        "__module__": "common_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.learningstore.historicaldecision.v2.api.Discriminator)
    },
)
_sym_db.RegisterMessage(Discriminator)


DESCRIPTOR._options = None
_WATCHLIST.fields_by_name["id"]._options = None
_WATCHLIST.fields_by_name["type"]._options = None
_DECISION.fields_by_name["id"]._options = None
_DECISION.fields_by_name["value"]._options = None
_DECISION.fields_by_name["created_at"]._options = None
_DISCRIMINATOR.fields_by_name["value"]._options = None
# @@protoc_insertion_point(module_scope)
