@Library('pipeline-shared-library') _

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: true,
    checkStyleEnabled: false,
    archiveArtifactsPattern: '**/build/libs/*.jar, plugins/**/*.jar',
    includeBuildNumberInSnapshotVersion: true,
    additionalParams: [
      extendedChoice(
        name: 'environments',
        value: 'dev,test',
        defaultValue: '',
        description: 'Environments to deploy to on Nomad',
        multiSelectDelimiter: ',',
        quoteValue: false,
        saveJSONParameterToFile: false,
        type: 'PT_MULTI_SELECT',
        visibleItemCount: 10)
    ],
    additionalStages: {
      deployOnNomad()
    }
)
