@Library('pipeline-shared-library') _

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: false,
    archiveArtifactsPattern: '**/build/libs/*.jar, plugins/**/*.jar',
    includeBuildNumberInSnapshotVersion: true
)
