package com.silenteight.searpayments.scb.etl.response;

public enum MessageFieldStructure {
  NAMEADDRESS_FORMAT_F, NAMEADDRESS_FORMAT_UNSTRUCTURED, NAMEADDRESS_FORMAT_LASTLINE_NAME,
  NAMEADDRESS_FORMAT_LASTLINE_EMAIL, UNSTRUCTURED
}
