# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import temp_hittype.hittype_pb2 as hittype__pb2


class HitTypeInputServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchGetMatchHitTypeInputs = channel.unary_stream(
            "/silenteight.datasource.api.hittype.v1.HitTypeInputService/BatchGetMatchHitTypeInputs",
            request_serializer=hittype__pb2.BatchGetMatchHitTypeInputsRequest.SerializeToString,
            response_deserializer=hittype__pb2.BatchGetMatchHitTypeInputsResponse.FromString,
        )


class HitTypeInputServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BatchGetMatchHitTypeInputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HitTypeInputServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "BatchGetMatchHitTypeInputs": grpc.unary_stream_rpc_method_handler(
            servicer.BatchGetMatchHitTypeInputs,
            request_deserializer=hittype__pb2.BatchGetMatchHitTypeInputsRequest.FromString,
            response_serializer=hittype__pb2.BatchGetMatchHitTypeInputsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "silenteight.datasource.api.hittype.v1.HitTypeInputService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class HitTypeInputService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BatchGetMatchHitTypeInputs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/silenteight.datasource.api.hittype.v1.HitTypeInputService/BatchGetMatchHitTypeInputs",
            hittype__pb2.BatchGetMatchHitTypeInputsRequest.SerializeToString,
            hittype__pb2.BatchGetMatchHitTypeInputsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
