@Library('pipeline-shared-library@master') _

def git = new com.silenteight.jenkins.ci.Git()

gradleBuild(
  jdkVersion: 'jdk-11',
  sonarEnabled: true,
  dependencyCheckEnabled: true,
  includeBuildNumberInSnapshotVersion: true,
  additionalParams: [
  extendedChoice(
    name: 'environments',
    value: 'dev,test,mike',
    defaultValue: '',
    description: 'Environments to deploy to on Nomad',
    multiSelectDelimiter: ',',
    quoteValue: false,
    saveJSONParameterToFile: false,
    type: 'PT_MULTI_SELECT',
    visibleItemCount: 10
   )
  ],
  additionalStages: {
    buildContainerImage()
    awsECR()
    helmChartRegistry()
    deployOnNomad()
    redeploySierraDev()
  }
)
