package com.silenteight.scb.ingest.adapter.incomming.common.indicator;

class RecordSignValues {

  static final String RECORD =
      "ECDDP~1008067637_CDD00104206_e51d4d82-3bd0-4fbf-91f9-12db0234d1eb~I~JIE CHEN~~~~~~~~~ROOM "
          + "315, KAIRUI TOWER A, NO.1, FENGCHENG 12 ROAD, XI'AN ECONOMIC & TECHNICAL DEVELOPMENT "
          + "ZONE~~~~~~~~~~~~CN~~~Passport~E04998527~~~~~~~~~1974-11-19~CN~~~~KE~~C~~Private "
          + "Company~Medium Enterprises~Medium Enterprise~ACTIVE~~2018-08-14~13727432_CDD00104206_"
          + "1.001~~~RELATED PARTY~N~|Beneficial Owner|~~1520790~~~~~No~~~~F~2018-11-29 "
          + "22:08:24.048~";

  static final String SOURCE_DETAILS =
      "\n"
          + "Source System Identifier: ECDDP\n"
          + "\n"
          + "Customer identification No: 1008067637_CDD00104206_e51d4d82-"
          + "3bd0-4fbf-91f9-12db0234d1eb\n"
          + "\n"
          + "Client Type: I\n"
          + "\n"
          + "Full Legal Name: JIE CHEN\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "Registered or Residential Address: ROOM 315, KAIRUI TOWER A, NO.1, FENGCHENG 12 ROAD, "
          + "XI'AN ECONOMIC & TECHNICAL DEVELOPMENT ZONE\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "Nationality all: CN\n"
          + "\n"
          + "\n"
          + "\n"
          + "Identification Type 1:\n"
          + "Passport\n"
          + "\n"
          + "Identification Number 1: \n"
          + "E04998527\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "Date of Birth or Registration: 1974-11-19\n"
          + "\n"
          + "Country of Birth or Registration: CN\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "AML Country: KE\n"
          + "\n"
          + "\n"
          + "CDD Risk Rating: C\n"
          + "\n"
          + "\n"
          + "  Private Company   \n"
          + "\n"
          + "Client Segment: Medium Enterprises\n"
          + "\n"
          + "Client Sub-Segment: Medium Enterprise\n"
          + "\n"
          + "Customer Status: ACTIVE\n"
          + "\n"
          + "\n"
          + "Last CDD Approved Date: 2018-08-14\n"
          + "\n"
          + "HOGAN Customer ID or Linked Customer Identification Number: "
          + "13727432_CDD00104206_1.001\n"
          + "\n"
          + "\n"
          + "\n"
          + "Party Type: RELATED PARTY\n"
          + "\n"
          + "PEP Status: N\n"
          + "\n"
          + "Supplementary Information 2: |Beneficial Owner|\n"
          + "\n"
          + "\n"
          + "RM Code of CDD Owner: 1520790\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "Supplementary Information 3: No\n"
          + "\n"
          + "\n"
          + "\n"
          + "\n"
          + "Change Indicator: F\n"
          + "\n"
          + "Date Time stamp: 2018-11-29 22:08:24.048\n"
          + "";

  static final String CLEANED_SOURCE_DETAILS =
      "ECDDP1008067637_CDD00104206_e51d4d82-3bd0-4fbf-91f9-12db0234d1ebIJIE CHENROOM 315, KAIRUI "
          + "TOWER A, NO.1, FENGCHENG 12 ROAD, XI'AN ECONOMIC & TECHNICAL DEVELOPMENT ZONE"
          + "CNPassportE049985271974-11-19CNKECPrivate CompanyMedium EnterprisesMedium"
          + " EnterpriseACTIVE2018-08-1413727432_CDD00104206_1.001RELATED PARTYN|Beneficial"
          + " Owner|1520790NoF2018-11-29 22:08:24.048";
}
