@Library('pipeline-shared-library') _
def utils = new com.silenteight.jenkins.ci.Utils()
def jenkins = new com.silenteight.jenkins.ci.Jenkins()

pipeline {
    agent none
    environment {
        PYPI_URL = credentials('pypi-readonly-url')
    }
    options {
        timeout(time: 1, unit: 'HOURS')   // just to be safe
    }

    stages {
        stage('Prepare python image') {
            agent any
            steps {
                sh 'docker pull python:3.7'
            }
        }
        stage('Prepare') {
            agent {
                docker {
                    image 'python:3.7'
                }
            }
            stages {
                stage('Build') {
                    steps {
                        sh './scripts/clean.sh'
                        sh './scripts/bootstrap.sh --index-url $PYPI_URL'
                        sh './scripts/build.sh --index-url $PYPI_URL'
                    }
                }
                stage('Prepare nomad artifact') {
                    steps {
                        sh './scripts/prepare_nomad_artifacts.sh'
                    }
                }
            }
            post {
                always {
                    junit '.tox/*.xml'
                    archiveArtifacts artifacts: 'dist/*', fingerprint: true
                }
                success {
                    stash includes: 'dist/*, nomad/artifacts/*', name: 'artifacts'
                }
            }
        }

        stage('Deployment'){
            agent {
                label 'nomad'   // TODO revert hack here
            stages {
                stage('Upload artifacts') {
                    steps {
                        sh './scripts/clean.sh'
                        unstash 'artifacts'
                        rtServer (
                            id: "silenteight-repo",
                            url: "https://repo.silenteight.com/artifactory",
                            credentialsId: "artifactory-deployment-user"
                        )
                        rtUpload (
                            serverId: 'silenteight-repo',
                            spec: '''{
                                  "files": [
                                    {
                                      "pattern": "dist/*.pyz",
                                      "target": "dist-public-local/bank-identification-codes-agent/"
                                    }
                                 ]
                            }''',
                        )
                        rtUpload (
                            serverId: 'silenteight-repo',
                            spec: '''{
                                  "files": [
                                    {
                                      "pattern": "dist/*.tgz",
                                      "target": "dist-public-local/bank-identification-codes-agent/"
                                    }
                                 ]
                            }''',
                        )
                    }
                }
                stage('Deploy on nomad dev') {
                    steps {
                       sh './nomad/deploy.sh'
                    }
                }
            }
       }
    }
}

