= Bank Identification Codes Agent

Previously known as Search Code Mismatch Agent.

== Usage
=== Installation
Module needs python >= 3.7. Tested only on python 3.7.

* from source:
pip install .

* from PiPY:
pip install bank-identification-codes-agent

* from jenkins artifacts:
https://jenkins.silenteight.com/job/id-mismatch-agent/job/master/


== Protobufs
Protobufs are available in:
https://gitlab.silenteight.com/ro/agents-api/-/blob/master/protocol-agents/src/main/proto/\
silenteight/agent/bankidentificationcodes/v1/api/bank_identification_codes_agent.proto

=== Execution
 python -m bank_identification_codes_agent [options]
 Optional arguments:
 -h, --help         Shows help message and exit
 -c CONFIGURATION_DIR, --configuration-dir CONFIGURATION_DIR
                    path to the configuration dir
 --grpc             Start grpc service
 --agent-exchange      Start agent exchange
 -v, --verbose      Increase verbosity for debug purpos

 When using .pyz file, to run type:
 python -m <file name>.pyz [options]

== Due-diligence question
Does the trigger text match against the search codes provided in the watchlist?

== Is agent decisive?
Yes

== Is agent tied to specific message?
Yes: SWIFT message type and SWIFT message tag but this is **not required** and should be removed as soon as possible.

== Agent output

[%Results,cols=2*]
|===
|Value
|Additional info

|MATCH
|Alert was triggred on search code, search code matches exactly so it looks like it could be potential true positive

|NO_DECISION
|Alert was not triggred on search code

|NO_MATCH
|Alert was triggered on search code but it was only partial match

|AGENT_ERROR
|internal errors

|===
