/*
 * HSCB-Bridge-batch API
 * HSCB-Bridge-batch API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * BatchProcessingStatusResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-02T11:57:31.043Z[GMT]")
public class BatchProcessingStatusResponse {
  @SerializedName("isAdjudicationEngineProcessing")
  private Boolean isAdjudicationEngineProcessing = null;

  public BatchProcessingStatusResponse isAdjudicationEngineProcessing(Boolean isAdjudicationEngineProcessing) {
    this.isAdjudicationEngineProcessing = isAdjudicationEngineProcessing;
    return this;
  }

   /**
   * Get isAdjudicationEngineProcessing
   * @return isAdjudicationEngineProcessing
  **/
  @Schema(description = "")
  public Boolean isIsAdjudicationEngineProcessing() {
    return isAdjudicationEngineProcessing;
  }

  public void setIsAdjudicationEngineProcessing(Boolean isAdjudicationEngineProcessing) {
    this.isAdjudicationEngineProcessing = isAdjudicationEngineProcessing;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchProcessingStatusResponse batchProcessingStatusResponse = (BatchProcessingStatusResponse) o;
    return Objects.equals(this.isAdjudicationEngineProcessing, batchProcessingStatusResponse.isAdjudicationEngineProcessing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isAdjudicationEngineProcessing);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchProcessingStatusResponse {\n");

    sb.append("    isAdjudicationEngineProcessing: ").append(toIndentedString(isAdjudicationEngineProcessing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
