### Start the recommendation process for batch request
POST {{baseUrl}}/rest/hsbc-bridge/async/batch/v1/26072021-100/recommend
Accept: application/json
Content-Type: application/json

< hsbc-bridge-request-full.json

### Start the recommendation process for single-alert request
POST {{baseUrl}}/rest/hsbc-bridge/async/batch/v1/26072021-200/recommend
Accept: application/json
Content-Type: application/json

< hsbc-bridge-request-single.json


### Check HSBC Bridge status
GET {{baseUrl}}/rest/hsbc-bridge/management/info
Accept: application/json


### Check the recommendation results
GET {{baseUrl}}/rest/hsbc-bridge/async/batch/v1/26072021-200/result
Accept: application/json
