### sear-customer-bridge
// @no-log
// @no-cookie-jar
// request-1.json.json
POST {{baseurl}}/rest/ftcc/v1/alert
Accept: application/json
Content-Type: application/json

< ./requests/request-simple.json

### Callback
// @no-log
// @no-cookie-jar
POST {{baseurl}}/rest/ftcc/callback
Accept: application/json
Content-Type: application/json

< ./requests/callback/callback-response-example-cmapi-trust.json
