# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etl_pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x65tl_pipeline.proto\x12*silenteight.datascience.etlpipeline.v1.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto"W\n\rRunEtlRequest\x12\x46\n\x06\x61lerts\x18\x01 \x03(\x0b\x32\x31.silenteight.datascience.etlpipeline.v1.api.AlertB\x03\xe0\x41\x02"\x93\x02\n\x05\x41lert\x12\x15\n\x08\x62\x61tch_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\nalert_name\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12G\n\x07matches\x18\x03 \x03(\x0b\x32\x31.silenteight.datascience.etlpipeline.v1.api.MatchB\x03\xe0\x41\x02\x12]\n\x0c\x66lat_payload\x18\x04 \x03(\x0b\x32\x42.silenteight.datascience.etlpipeline.v1.api.Alert.FlatPayloadEntryB\x03\xe0\x41\x02\x1a\x32\n\x10\x46latPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"7\n\x05Match\x12\x15\n\x08match_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\nmatch_name\x18\x02 \x01(\tB\x03\xe0\x41\x02"_\n\x0eRunEtlResponse\x12M\n\netl_alerts\x18\x01 \x03(\x0b\x32\x34.silenteight.datascience.etlpipeline.v1.api.EtlAlertB\x03\xe0\x41\x02"\xda\x01\n\x08\x45tlAlert\x12\x15\n\x08\x62\x61tch_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\nalert_name\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12N\n\netl_status\x18\x03 \x01(\x0e\x32\x35.silenteight.datascience.etlpipeline.v1.api.EtlStatusB\x03\xe0\x41\x02\x12N\n\x0b\x65tl_matches\x18\x04 \x03(\x0b\x32\x34.silenteight.datascience.etlpipeline.v1.api.EtlMatchB\x03\xe0\x41\x02"#\n\x08\x45tlMatch\x12\x17\n\nmatch_name\x18\x01 \x01(\tB\x03\xe0\x41\x02*2\n\tEtlStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x32\xb6\x01\n\x12\x45tlPipelineService\x12\x9f\x01\n\x06RunEtl\x12\x39.silenteight.datascience.etlpipeline.v1.api.RunEtlRequest\x1a:.silenteight.datascience.etlpipeline.v1.api.RunEtlResponse"\x1e\x82\xd3\xe4\x93\x02\x18"\x0e/v1/etl:runEtl:\x06runEtlBG\n.com.silenteight.datascience.etlpipeline.v1.apiB\x13\x45tlPipelineApiProtoP\x01\x62\x06proto3'
)

_ETLSTATUS = DESCRIPTOR.enum_types_by_name["EtlStatus"]
EtlStatus = enum_type_wrapper.EnumTypeWrapper(_ETLSTATUS)
UNKNOWN = 0
FAILURE = 1
SUCCESS = 2


_RUNETLREQUEST = DESCRIPTOR.message_types_by_name["RunEtlRequest"]
_ALERT = DESCRIPTOR.message_types_by_name["Alert"]
_ALERT_FLATPAYLOADENTRY = _ALERT.nested_types_by_name["FlatPayloadEntry"]
_MATCH = DESCRIPTOR.message_types_by_name["Match"]
_RUNETLRESPONSE = DESCRIPTOR.message_types_by_name["RunEtlResponse"]
_ETLALERT = DESCRIPTOR.message_types_by_name["EtlAlert"]
_ETLMATCH = DESCRIPTOR.message_types_by_name["EtlMatch"]
RunEtlRequest = _reflection.GeneratedProtocolMessageType(
    "RunEtlRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RUNETLREQUEST,
        "__module__": "etl_pipeline_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.RunEtlRequest)
    },
)
_sym_db.RegisterMessage(RunEtlRequest)

Alert = _reflection.GeneratedProtocolMessageType(
    "Alert",
    (_message.Message,),
    {
        "FlatPayloadEntry": _reflection.GeneratedProtocolMessageType(
            "FlatPayloadEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _ALERT_FLATPAYLOADENTRY,
                "__module__": "etl_pipeline_pb2"
                # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.Alert.FlatPayloadEntry)
            },
        ),
        "DESCRIPTOR": _ALERT,
        "__module__": "etl_pipeline_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.Alert)
    },
)
_sym_db.RegisterMessage(Alert)
_sym_db.RegisterMessage(Alert.FlatPayloadEntry)

Match = _reflection.GeneratedProtocolMessageType(
    "Match",
    (_message.Message,),
    {
        "DESCRIPTOR": _MATCH,
        "__module__": "etl_pipeline_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.Match)
    },
)
_sym_db.RegisterMessage(Match)

RunEtlResponse = _reflection.GeneratedProtocolMessageType(
    "RunEtlResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _RUNETLRESPONSE,
        "__module__": "etl_pipeline_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.RunEtlResponse)
    },
)
_sym_db.RegisterMessage(RunEtlResponse)

EtlAlert = _reflection.GeneratedProtocolMessageType(
    "EtlAlert",
    (_message.Message,),
    {
        "DESCRIPTOR": _ETLALERT,
        "__module__": "etl_pipeline_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.EtlAlert)
    },
)
_sym_db.RegisterMessage(EtlAlert)

EtlMatch = _reflection.GeneratedProtocolMessageType(
    "EtlMatch",
    (_message.Message,),
    {
        "DESCRIPTOR": _ETLMATCH,
        "__module__": "etl_pipeline_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etlpipeline.v1.api.EtlMatch)
    },
)
_sym_db.RegisterMessage(EtlMatch)

_ETLPIPELINESERVICE = DESCRIPTOR.services_by_name["EtlPipelineService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n.com.silenteight.datascience.etlpipeline.v1.apiB\023EtlPipelineApiProtoP\001"
    )
    _RUNETLREQUEST.fields_by_name["alerts"]._options = None
    _RUNETLREQUEST.fields_by_name["alerts"]._serialized_options = b"\340A\002"
    _ALERT_FLATPAYLOADENTRY._options = None
    _ALERT_FLATPAYLOADENTRY._serialized_options = b"8\001"
    _ALERT.fields_by_name["batch_id"]._options = None
    _ALERT.fields_by_name["batch_id"]._serialized_options = b"\340A\002"
    _ALERT.fields_by_name["alert_name"]._options = None
    _ALERT.fields_by_name["alert_name"]._serialized_options = b"\340A\002"
    _ALERT.fields_by_name["matches"]._options = None
    _ALERT.fields_by_name["matches"]._serialized_options = b"\340A\002"
    _ALERT.fields_by_name["flat_payload"]._options = None
    _ALERT.fields_by_name["flat_payload"]._serialized_options = b"\340A\002"
    _MATCH.fields_by_name["match_id"]._options = None
    _MATCH.fields_by_name["match_id"]._serialized_options = b"\340A\002"
    _MATCH.fields_by_name["match_name"]._options = None
    _MATCH.fields_by_name["match_name"]._serialized_options = b"\340A\002"
    _RUNETLRESPONSE.fields_by_name["etl_alerts"]._options = None
    _RUNETLRESPONSE.fields_by_name["etl_alerts"]._serialized_options = b"\340A\002"
    _ETLALERT.fields_by_name["batch_id"]._options = None
    _ETLALERT.fields_by_name["batch_id"]._serialized_options = b"\340A\002"
    _ETLALERT.fields_by_name["alert_name"]._options = None
    _ETLALERT.fields_by_name["alert_name"]._serialized_options = b"\340A\002"
    _ETLALERT.fields_by_name["etl_status"]._options = None
    _ETLALERT.fields_by_name["etl_status"]._serialized_options = b"\340A\002"
    _ETLALERT.fields_by_name["etl_matches"]._options = None
    _ETLALERT.fields_by_name["etl_matches"]._serialized_options = b"\340A\002"
    _ETLMATCH.fields_by_name["match_name"]._options = None
    _ETLMATCH.fields_by_name["match_name"]._serialized_options = b"\340A\002"
    _ETLPIPELINESERVICE.methods_by_name["RunEtl"]._options = None
    _ETLPIPELINESERVICE.methods_by_name[
        "RunEtl"
    ]._serialized_options = b'\202\323\344\223\002\030"\016/v1/etl:runEtl:\006runEtl'
    _ETLSTATUS._serialized_start = 908
    _ETLSTATUS._serialized_end = 958
    _RUNETLREQUEST._serialized_start = 129
    _RUNETLREQUEST._serialized_end = 216
    _ALERT._serialized_start = 219
    _ALERT._serialized_end = 494
    _ALERT_FLATPAYLOADENTRY._serialized_start = 444
    _ALERT_FLATPAYLOADENTRY._serialized_end = 494
    _MATCH._serialized_start = 496
    _MATCH._serialized_end = 551
    _RUNETLRESPONSE._serialized_start = 553
    _RUNETLRESPONSE._serialized_end = 648
    _ETLALERT._serialized_start = 651
    _ETLALERT._serialized_end = 869
    _ETLMATCH._serialized_start = 871
    _ETLMATCH._serialized_end = 906
    _ETLPIPELINESERVICE._serialized_start = 961
    _ETLPIPELINESERVICE._serialized_end = 1143
# @@protoc_insertion_point(module_scope)
