{
 "title": "Solving / Learning",
 "description": "Dashboard for Delta Team",
 "tags": [
  "ae",
  "bridge",
  "svb",
  "uds"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(jvm_threads_live_threads, application)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_threads_live_threads{application=~\"$application\"}, instance)"
    }
   },
   {
    "name": "className",
    "query": {
     "query": "label_values(method_timed_seconds_count{application=~\"$application\", instance=~\"$instance\"}, class)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(method_timed_seconds_count{application=~\"$application\", instance=~\"$instance\", class=~\"$className\"}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Whole time processing in AE ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(method_timed_seconds_bucket{application=~\"$application\", instance=~\"$instance\", class=\"com.silenteight.adjudication.engine.solving.application.listener.ReceivedAlertListener\", method=\"onReceivedAlert\"}[$__rate_interval])) by (le)) + histogram_quantile(0.95, sum(rate(method_timed_seconds_bucket{application=~\"$application\", instance=~\"$instance\", class=\"com.silenteight.adjudication.engine.solving.application.listener.ReceiveAgentResponseListener\", method=\"onReceive\"}[$__rate_interval])) by (le)) ) ",
     "legendFormat": "dupa"
    }
   ]
  },
  { "title": "Bridge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Message store in warehouse outbound ",
   "type": "timeseries",
   "description": "Time to execute log ( :D ) before passing data to outbound",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(message_store_in_warehouse_outbound_seconds_bucket{application=~\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, application , instance, endpoint))",
     "legendFormat": "{{application }} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total Processing Solving and Learning Alerts ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pb_solving_and_learning_alerts_total[$__rate_interval])) by (application, instance, service, type) * 100",
     "legendFormat": "{{instance}} - {{service}} - {{ type }} "
    }
   ]
  },
  { "title": "AE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Rate of learning solving alerts in AE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(learning_solving_alerts{application=~\"$application\", instance=~\"$instance\"}[$__rate_interval])) by ( application, instance, type)",
     "legendFormat": "{{application }} - {{type}}"
    }
   ]
  },
  { "title": "Method executions ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Status Queue Overflowed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(alert_status_queue_overflowed{application=~\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (application, instance)",
     "legendFormat": "{{application }} - {{instance}}"
    }
   ]
  },
  {
   "title": "$className - $method",
   "type": "timeseries",
   "description": "Execution time for a particular $method  in the $className. ",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 41 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(method_timed_seconds_bucket{application=~\"$application\", instance=~\"$instance\", class=~\"$className\", method=~\"$method\"}[$__rate_interval])) by (le, application, instance, class, method))",
     "legendFormat": "{{ application }} - {{ instance }} - {{class}} - {{instance}}"
    }
   ]
  }
 ]
}