# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import company_name.agent.config_service.organization_name_agent_config_pb2 as organization__name__agent__config__pb2


class OrganizationNameAgentConfigStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChangeOrganizationNameAgentConfig = channel.unary_unary(
            "/OrganizationNameAgentConfig/ChangeOrganizationNameAgentConfig",
            request_serializer=organization__name__agent__config__pb2.ChangeOrganizationNameAgentConfigRequest.SerializeToString,
            response_deserializer=organization__name__agent__config__pb2.ChangeOrganizationNameAgentConfigResponse.FromString,
        )


class OrganizationNameAgentConfigServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChangeOrganizationNameAgentConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrganizationNameAgentConfigServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ChangeOrganizationNameAgentConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ChangeOrganizationNameAgentConfig,
            request_deserializer=organization__name__agent__config__pb2.ChangeOrganizationNameAgentConfigRequest.FromString,
            response_serializer=organization__name__agent__config__pb2.ChangeOrganizationNameAgentConfigResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "OrganizationNameAgentConfig", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class OrganizationNameAgentConfig(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChangeOrganizationNameAgentConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/OrganizationNameAgentConfig/ChangeOrganizationNameAgentConfig",
            organization__name__agent__config__pb2.ChangeOrganizationNameAgentConfigRequest.SerializeToString,
            organization__name__agent__config__pb2.ChangeOrganizationNameAgentConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
