# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organization_name_agent_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="organization_name_agent_config.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n$organization_name_agent_config.proto"\xa0\x02\n(ChangeOrganizationNameAgentConfigRequest\x12#\n\rfeature_rules\x18\x01 \x03(\x0b\x32\x0c.FeatureRule\x12\x30\n\x14model_solution_rules\x18\x02 \x03(\x0b\x32\x12.ModelSolutionRule\x12\x12\n\nmodel_path\x18\x03 \x01(\t\x12-\n\x12name_alphabet_rule\x18\x04 \x01(\x0b\x32\x11.NameAlphabetRule\x12/\n\x13name_inclusion_rule\x18\x05 \x01(\x0b\x32\x12.NameInclusionRule\x12)\n\x10name_length_rule\x18\x06 \x01(\x0b\x32\x0f.NameLengthRule"l\n\x0b\x46\x65\x61tureRule\x12\x11\n\tthreshold\x18\x01 \x01(\x02\x12\x0f\n\x07\x66\x65\x61ture\x18\x02 \x01(\t\x12\x1b\n\x08solution\x18\x03 \x01(\x0e\x32\t.Solution\x12\x1c\n\x14solution_probability\x18\x04 \x01(\x02"R\n\x11ModelSolutionRule\x12\x1b\n\x08solution\x18\x01 \x01(\x0e\x32\t.Solution\x12\x11\n\tthreshold\x18\x02 \x01(\x02\x12\r\n\x05label\x18\x03 \x01(\t"Q\n\x10NameAlphabetRule\x12\x1f\n\x17min_acceptable_fraction\x18\x01 \x01(\x02\x12\x1c\n\x14\x61\x63\x63\x65ptable_alphabets\x18\x02 \x03(\t"@\n\x11NameInclusionRule\x12\x14\n\x0cwithout_part\x18\x01 \x03(\t\x12\x15\n\rwithout_token\x18\x02 \x03(\t"?\n\x0eNameLengthRule\x12\x12\n\nmax_length\x18\x01 \x01(\r\x12\x19\n\x11max_unique_tokens\x18\x02 \x01(\r"\x8b\x01\n)ChangeOrganizationNameAgentConfigResponse\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.ChangeOrganizationNameAgentConfigResponse.Status"\x1b\n\x06Status\x12\t\n\x05\x45RROR\x10\x00\x12\x06\n\x02OK\x10\x01*S\n\x08Solution\x12\t\n\x05MATCH\x10\x00\x12\x10\n\x0cINCONCLUSIVE\x10\x01\x12\x0c\n\x08NO_MATCH\x10\x02\x12\x0b\n\x07NO_DATA\x10\x03\x12\x0f\n\x0b\x41GENT_ERROR\x10\x04\x32\x9b\x01\n\x1bOrganizationNameAgentConfig\x12|\n!ChangeOrganizationNameAgentConfig\x12).ChangeOrganizationNameAgentConfigRequest\x1a*.ChangeOrganizationNameAgentConfigResponse"\x00\x62\x06proto3',
)

_SOLUTION = _descriptor.EnumDescriptor(
    name="Solution",
    full_name="Solution",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="MATCH",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="INCONCLUSIVE",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="NO_MATCH",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="NO_DATA",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="AGENT_ERROR",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=881,
    serialized_end=964,
)
_sym_db.RegisterEnumDescriptor(_SOLUTION)

Solution = enum_type_wrapper.EnumTypeWrapper(_SOLUTION)
MATCH = 0
INCONCLUSIVE = 1
NO_MATCH = 2
NO_DATA = 3
AGENT_ERROR = 4


_CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE_STATUS = _descriptor.EnumDescriptor(
    name="Status",
    full_name="ChangeOrganizationNameAgentConfigResponse.Status",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="ERROR",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="OK",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=852,
    serialized_end=879,
)
_sym_db.RegisterEnumDescriptor(_CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE_STATUS)


_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST = _descriptor.Descriptor(
    name="ChangeOrganizationNameAgentConfigRequest",
    full_name="ChangeOrganizationNameAgentConfigRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="feature_rules",
            full_name="ChangeOrganizationNameAgentConfigRequest.feature_rules",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="model_solution_rules",
            full_name="ChangeOrganizationNameAgentConfigRequest.model_solution_rules",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="model_path",
            full_name="ChangeOrganizationNameAgentConfigRequest.model_path",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name_alphabet_rule",
            full_name="ChangeOrganizationNameAgentConfigRequest.name_alphabet_rule",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name_inclusion_rule",
            full_name="ChangeOrganizationNameAgentConfigRequest.name_inclusion_rule",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name_length_rule",
            full_name="ChangeOrganizationNameAgentConfigRequest.name_length_rule",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=41,
    serialized_end=329,
)


_FEATURERULE = _descriptor.Descriptor(
    name="FeatureRule",
    full_name="FeatureRule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="threshold",
            full_name="FeatureRule.threshold",
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="feature",
            full_name="FeatureRule.feature",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="solution",
            full_name="FeatureRule.solution",
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="solution_probability",
            full_name="FeatureRule.solution_probability",
            index=3,
            number=4,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=331,
    serialized_end=439,
)


_MODELSOLUTIONRULE = _descriptor.Descriptor(
    name="ModelSolutionRule",
    full_name="ModelSolutionRule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="solution",
            full_name="ModelSolutionRule.solution",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="threshold",
            full_name="ModelSolutionRule.threshold",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="label",
            full_name="ModelSolutionRule.label",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=441,
    serialized_end=523,
)


_NAMEALPHABETRULE = _descriptor.Descriptor(
    name="NameAlphabetRule",
    full_name="NameAlphabetRule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="min_acceptable_fraction",
            full_name="NameAlphabetRule.min_acceptable_fraction",
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="acceptable_alphabets",
            full_name="NameAlphabetRule.acceptable_alphabets",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=525,
    serialized_end=606,
)


_NAMEINCLUSIONRULE = _descriptor.Descriptor(
    name="NameInclusionRule",
    full_name="NameInclusionRule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="without_part",
            full_name="NameInclusionRule.without_part",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="without_token",
            full_name="NameInclusionRule.without_token",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=608,
    serialized_end=672,
)


_NAMELENGTHRULE = _descriptor.Descriptor(
    name="NameLengthRule",
    full_name="NameLengthRule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="max_length",
            full_name="NameLengthRule.max_length",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="max_unique_tokens",
            full_name="NameLengthRule.max_unique_tokens",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=674,
    serialized_end=737,
)


_CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE = _descriptor.Descriptor(
    name="ChangeOrganizationNameAgentConfigResponse",
    full_name="ChangeOrganizationNameAgentConfigResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="ChangeOrganizationNameAgentConfigResponse.status",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE_STATUS,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=740,
    serialized_end=879,
)

_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST.fields_by_name[
    "feature_rules"
].message_type = _FEATURERULE
_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST.fields_by_name[
    "model_solution_rules"
].message_type = _MODELSOLUTIONRULE
_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST.fields_by_name[
    "name_alphabet_rule"
].message_type = _NAMEALPHABETRULE
_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST.fields_by_name[
    "name_inclusion_rule"
].message_type = _NAMEINCLUSIONRULE
_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST.fields_by_name[
    "name_length_rule"
].message_type = _NAMELENGTHRULE
_FEATURERULE.fields_by_name["solution"].enum_type = _SOLUTION
_MODELSOLUTIONRULE.fields_by_name["solution"].enum_type = _SOLUTION
_CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE.fields_by_name[
    "status"
].enum_type = _CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE_STATUS
_CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE_STATUS.containing_type = (
    _CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE
)
DESCRIPTOR.message_types_by_name[
    "ChangeOrganizationNameAgentConfigRequest"
] = _CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST
DESCRIPTOR.message_types_by_name["FeatureRule"] = _FEATURERULE
DESCRIPTOR.message_types_by_name["ModelSolutionRule"] = _MODELSOLUTIONRULE
DESCRIPTOR.message_types_by_name["NameAlphabetRule"] = _NAMEALPHABETRULE
DESCRIPTOR.message_types_by_name["NameInclusionRule"] = _NAMEINCLUSIONRULE
DESCRIPTOR.message_types_by_name["NameLengthRule"] = _NAMELENGTHRULE
DESCRIPTOR.message_types_by_name[
    "ChangeOrganizationNameAgentConfigResponse"
] = _CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE
DESCRIPTOR.enum_types_by_name["Solution"] = _SOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangeOrganizationNameAgentConfigRequest = _reflection.GeneratedProtocolMessageType(
    "ChangeOrganizationNameAgentConfigRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:ChangeOrganizationNameAgentConfigRequest)
    },
)
_sym_db.RegisterMessage(ChangeOrganizationNameAgentConfigRequest)

FeatureRule = _reflection.GeneratedProtocolMessageType(
    "FeatureRule",
    (_message.Message,),
    {
        "DESCRIPTOR": _FEATURERULE,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:FeatureRule)
    },
)
_sym_db.RegisterMessage(FeatureRule)

ModelSolutionRule = _reflection.GeneratedProtocolMessageType(
    "ModelSolutionRule",
    (_message.Message,),
    {
        "DESCRIPTOR": _MODELSOLUTIONRULE,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:ModelSolutionRule)
    },
)
_sym_db.RegisterMessage(ModelSolutionRule)

NameAlphabetRule = _reflection.GeneratedProtocolMessageType(
    "NameAlphabetRule",
    (_message.Message,),
    {
        "DESCRIPTOR": _NAMEALPHABETRULE,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:NameAlphabetRule)
    },
)
_sym_db.RegisterMessage(NameAlphabetRule)

NameInclusionRule = _reflection.GeneratedProtocolMessageType(
    "NameInclusionRule",
    (_message.Message,),
    {
        "DESCRIPTOR": _NAMEINCLUSIONRULE,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:NameInclusionRule)
    },
)
_sym_db.RegisterMessage(NameInclusionRule)

NameLengthRule = _reflection.GeneratedProtocolMessageType(
    "NameLengthRule",
    (_message.Message,),
    {
        "DESCRIPTOR": _NAMELENGTHRULE,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:NameLengthRule)
    },
)
_sym_db.RegisterMessage(NameLengthRule)

ChangeOrganizationNameAgentConfigResponse = _reflection.GeneratedProtocolMessageType(
    "ChangeOrganizationNameAgentConfigResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE,
        "__module__": "organization_name_agent_config_pb2"
        # @@protoc_insertion_point(class_scope:ChangeOrganizationNameAgentConfigResponse)
    },
)
_sym_db.RegisterMessage(ChangeOrganizationNameAgentConfigResponse)


_ORGANIZATIONNAMEAGENTCONFIG = _descriptor.ServiceDescriptor(
    name="OrganizationNameAgentConfig",
    full_name="OrganizationNameAgentConfig",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=967,
    serialized_end=1122,
    methods=[
        _descriptor.MethodDescriptor(
            name="ChangeOrganizationNameAgentConfig",
            full_name="OrganizationNameAgentConfig.ChangeOrganizationNameAgentConfig",
            index=0,
            containing_service=None,
            input_type=_CHANGEORGANIZATIONNAMEAGENTCONFIGREQUEST,
            output_type=_CHANGEORGANIZATIONNAMEAGENTCONFIGRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ORGANIZATIONNAMEAGENTCONFIG)

DESCRIPTOR.services_by_name["OrganizationNameAgentConfig"] = _ORGANIZATIONNAMEAGENTCONFIG

# @@protoc_insertion_point(module_scope)
