from enum import Enum

from etl_pipeline.config import pipeline_config

cn = pipeline_config.cn


ACCT_CLAS_DESCR = "ACCT_CLAS_DESCR"
ACCT_NUM = "ACCT_NUM"
ACCT_PMH_ADDR_ID = "ACCT_PMH_ADDR_ID"
ACCT_REGS_NM1 = "ACCT_REGS_NM1"
ADDRESS_ID = "ADDRESS_ID"
ALERTED_PARTY_NAME = "ALERTED_PARTY_NAME"
ALERT_ID = "alert_id"
AP_PARTIES_NAMES = "all_connected_parties_names"
AP_PARTY_DETAILS = "AP_PARTY_DETAILS"
AP_PARTS_NAMES = "AP_PARTS_NAMES"
CONCAT_RESIDUE = "concat_residue"
CONNECTED_FULL_NAME = "CONNECTED_FULL_NAME"
DOB_DT = "DOB_DT"
PARTY_ID = "PARTY_ID"
PRTY_CNTRY_OF_BIRTH = "PRTY_CNTRY_OF_BIRTH"
PRTY_FST_NM = "PRTY_FST_NM"
PRTY_ID = "PRTY_ID"
PRTY_LST_NM = "PRTY_LST_NM"
PRTY_MDL_NM = "PRTY_MDL_NM"
PRTY_NM = "PRTY_NM"
PRTY_PRIM_CTZNSH_CNTRY = "PRTY_PRIM_CTZNSH_CNTRY"
PRTY_RSDNC_CNTRY_CD = "PRTY_RSDNC_CNTRY_CD"
TAX_ID_TYP_ID = "TAX_ID_TYP_ID"
PRTY_TYP = "PRTY_TYP"
MERGING_PARTIES = [
    PARTY_ID,
    PRTY_TYP,
    PRTY_NM,
    PRTY_FST_NM,
    PRTY_LST_NM,
    PRTY_MDL_NM,
    TAX_ID_TYP_ID,
    DOB_DT,
    PRTY_CNTRY_OF_BIRTH,
    PRTY_PRIM_CTZNSH_CNTRY,
    PRTY_RSDNC_CNTRY_CD,
]

PARTIES = "parties"
ACCOUNTS = "accounts"
CONNECTED_FULL_NAME = "CONNECTED_FULL_NAME"
AP_PARTY_TYPES = "AP_PARTY_TYPES"
ENTITY_ID = "ENTITY_ID"
ENTITY_VERSION = "ENTITY_VERSION"
IS_BENEFICIARY_HIT = "is_beneficiary_hit"
MATCH_ID = "match_id"
MATCH_INPUT_VERSION_ID = "MATCH_INPUT_VERSION_ID"
MATCH_RECORDS = "match_ids"
NUMBER_OF_HITS = "number_of_hits"
SRC_REF_KEY = "SRC_REF_KEY"
SRC_SYS_ACCT_KEY = "SRC_SYS_ACCT_KEY"


class AccountType(str, Enum):
    WM_ADDRESS = "WM_ADDRESS"
    ISG_ACCOUNT = "ISG_ACCOUNT"
