import collections
import unidecode


COUNTRIES = [
    {"Afghanistan", "The Islamic Republic of Afghanistan", "AF", "AFG"},
    {"Åland Islands", "Åland", "AX", "ALA"},
    {"Albania", "The Republic of Albania", "AL", "ALB"},
    {"Algeria", "The People's Democratic Republic of Algeria", "DZ", "DZA"},
    {"American Samoa", "The Territory of American Samoa", "AS", "ASM"},
    {"Andorra", "The Principality of Andorra", "AD", "AND"},
    {"Angola", "The Republic of Angola", "AO", "AGO"},
    {"Anguilla", "Anguilla", "AI", "AIA"},
    {
        "Antarctica",
        "AQ",
        "ATA",
    },
    {"Antigua and Barbuda", "Antigua and Barbuda", "AG", "ATG"},
    {"Argentina", "The Argentine Republic", "AR", "ARG"},
    {"Armenia", "The Republic of Armenia", "AM", "ARM"},
    {"Aruba", "AW", "ABW"},
    {"Australia", "The Commonwealth of Australia", "AU", "AUS"},
    {"Austria", "The Republic of Austria", "AT", "AUT"},
    {"Azerbaijan", "The Republic of Azerbaijan", "AZ", "AZE"},
    {"Bahamas", "The Bahamas", "The Commonwealth of The Bahamas", "BS", "BHS"},
    {"Bahrain", "The Kingdom of Bahrain", "BH", "BHR"},
    {"Bangladesh", "The People's Republic of Bangladesh", "BD", "BGD"},
    {"Barbados", "BB", "BRB"},
    {"Belarus", "The Republic of Belarus", "BY", "BLR"},
    {"Belgium", "The Kingdom of Belgium", "BE", "BEL"},
    {"Belize", "Belize", "BZ", "BLZ"},
    {"Benin", "The Republic of Benin", "BJ", "BEN"},
    {"Bermuda", "Bermuda", "BM", "BMU"},
    {"Bhutan", "The Kingdom of Bhutan", "BT", "BTN"},
    {
        "Bolivia",
        "The Plurinational State of Bolivia",
        "BO",
        "BOL",
    },
    {"Bonaire, Sint Eustatius and Saba", "BQ", "BES"},
    {"Bosnia and Herzegovina", "Bosnia and Herzegovina", "BA", "BIH"},
    {"Botswana", "The Republic of Botswana", "BW", "BWA"},
    {"Bouvet Island", "Bouvet Island", "BV", "BVT"},
    {"Brazil", "The Federative Republic of Brazil", "BR", "BRA"},
    {
        "British Indian Ocean Territory",
        "The British Indian Ocean Territory",
        "IO",
        "IOT",
    },
    {"Brunei Darussalam", "The Nation of Brunei, the Abode of Peace", "BN", "BRN"},
    {"Bulgaria", "The Republic of Bulgaria", "BG", "BGR"},
    {"Burkina Faso", "Burkina Faso", "BF", "BFA"},
    {"Burundi", "The Republic of Burundi", "BI", "BDI"},
    {"Cabo Verde", "The Republic of Cabo Verde", "CV", "CPV"},
    {"Cambodia", "The Kingdom of Cambodia", "KH", "KHM"},
    {"Cameroon", "The Republic of Cameroon", "CM", "CMR"},
    {"Canada", "Canada", "CA", "CAN"},
    {"Cayman Islands", "The Cayman Islands", "KY", "CYM"},
    {"Central African Republic", "The Central African Republic", "CF", "CAF"},
    {"Chad", "The Republic of Chad", "TD", "TCD"},
    {"Chile", "The Republic of Chile", "CL", "CHL"},
    {"China", "The People's Republic of China", "CN", "CHN"},
    {"Christmas Island", "The Territory of Christmas Island", "CX", "CXR"},
    {
        "Cocos (Keeling) Islands",
        "The Cocos (Keeling) Islands",
        "The Territory of Cocos (Keeling) Islands",
        "CC",
        "CCK",
    },
    {"Colombia", "The Republic of Colombia", "CO", "COL"},
    {"Comoros", "The Comoros", "The Union of the Comoros", "KM", "COM"},
    {
        "Congo",
        "The Democratic Republic of the Congo",
        "CD",
        "COD",
    },
    {"Congo", "The Congo", "The Republic of the Congo", "CG", "COG"},
    {"Cook Islands", "The Cook Islands", "CK", "COK"},
    {"Costa Rica", "The Republic of Costa Rica", "CR", "CRI"},
    {"Côte d'Ivoire", "The Republic of Côte d'Ivoire", "CI", "CIV"},
    {"Croatia", "The Republic of Croatia", "HR", "HRV"},
    {"Cuba", "The Republic of Cuba", "CU", "CUB"},
    {"Curaçao", "The Country of Curaçao", "CW", "CUW"},
    {"Cyprus", "The Republic of Cyprus", "CY", "CYP"},
    {"Czechia", "The Czech Republic", "CZ", "CZE"},
    {"Denmark", "The Kingdom of Denmark", "DK", "DNK"},
    {"Djibouti", "The Republic of Djibouti", "DJ", "DJI"},
    {"Dominica", "The Commonwealth of Dominica", "DM", "DMA"},
    {"Dominican Republic", "The Dominican Republic", "DO", "DOM"},
    {"Ecuador", "The Republic of Ecuador", "EC", "ECU"},
    {"Egypt", "The Arab Republic of Egypt", "EG", "EGY"},
    {"El Salvador", "The Republic of El Salvador", "SV", "SLV"},
    {"Equatorial Guinea", "The Republic of Equatorial Guinea", "GQ", "GNQ"},
    {"Eritrea", "The State of Eritrea", "ER", "ERI"},
    {"Estonia", "The Republic of Estonia", "EE", "EST"},
    {"Eswatini", "The Kingdom of Eswatini", "SZ", "SWZ"},
    {"Ethiopia", "The Federal Democratic Republic of Ethiopia", "ET", "ETH"},
    {"Falkland Islands", "The Falkland Islands", "FK", "FLK"},
    {"Faroe Islands", "The Faroe Islands", "FO", "FRO"},
    {"Fiji", "The Republic of Fiji", "FJ", "FJI"},
    {"Finland", "The Republic of Finland", "FI", "FIN"},
    {"France", "The French Republic", "FR", "FRA"},
    {"French Guiana", "Guyane", "GF", "GUF"},
    {"French Polynesia", "French Polynesia", "PF", "PYF"},
    {
        "French Southern Territories",
        "The French Southern Territories",
        "The French Southern and Antarctic Lands",
        "TF",
        "ATF",
    },
    {"Gabon", "The Gabonese Republic", "GA", "GAB"},
    {"Gambia", "The Gambia", "The Republic of The Gambia", "GM", "GMB"},
    {"Georgia", "Georgia", "GE", "GEO"},
    {"Germany", "The Federal Republic of Germany", "DE", "DEU"},
    {"Ghana", "The Republic of Ghana", "GH", "GHA"},
    {"Gibraltar", "Gibraltar", "GI", "GIB"},
    {"Greece", "The Hellenic Republic", "GR", "GRC"},
    {"Greenland", "Kalaallit Nunaat", "GL", "GRL"},
    {"Grenada", "Grenada", "GD", "GRD"},
    {"Guadeloupe", "Guadeloupe", "GP", "GLP"},
    {"Guam", "The Territory of Guam", "GU", "GUM"},
    {"Guatemala", "The Republic of Guatemala", "GT", "GTM"},
    {"Guernsey", "The Bailiwick of Guernsey", "GG", "GGY"},
    {"Guinea", "The Republic of Guinea", "GN", "GIN"},
    {"Guinea-Bissau", "The Republic of Guinea-Bissau", "GW", "GNB"},
    {"Guyana", "The Co-operative Republic of Guyana", "GY", "GUY"},
    {"Haiti", "The Republic of Haiti", "HT", "HTI"},
    {
        "Heard Island and McDonald Islands",
        "The Territory of Heard Island and McDonald Islands",
        "HM",
        "HMD",
    },
    {"Holy See", "The Holy See", "VA", "VAT"},
    {"Honduras", "The Republic of Honduras", "HN", "HND"},
    {
        "Hong Kong",
        "The Hong Kong Special Administrative Region of China",
        "HK",
        "HKG",
    },
    {"Hungary", "Hungary", "HU", "HUN"},
    {"Iceland", "Iceland", "IS", "ISL"},
    {"India", "The Republic of India", "IN", "IND"},
    {"Indonesia", "The Republic of Indonesia", "ID", "IDN"},
    {"Iran", "The Islamic Republic of Iran", "IR", "IRN"},
    {"Iraq", "The Republic of Iraq", "IQ", "IRQ"},
    {"Ireland", "Ireland", "IE", "IRL"},
    {"Isle of Man", "The Isle of Man", "IM", "IMN"},
    {"Israel", "The State of Israel", "IL", "ISR"},
    {"Italy", "The Italian Republic", "IT", "ITA"},
    {"Jamaica", "Jamaica", "JM", "JAM"},
    {"Japan", "Japan", "JP", "JPN"},
    {"Jersey", "The Bailiwick of Jersey", "JE", "JEY"},
    {"Jordan", "The Hashemite Kingdom of Jordan", "JO", "JOR"},
    {"Kazakhstan", "The Republic of Kazakhstan", "KZ", "KAZ"},
    {"Kenya", "The Republic of Kenya", "KE", "KEN"},
    {"Kiribati", "The Republic of Kiribati", "KI", "KIR"},
    {
        "Korea",
        "North Korea",
        "The Democratic People's Republic of Korea",
        "KP",
        "PRK",
        "DPRK",
        "DPR Korea",
    },
    {"Korea", "South Korea", "The Republic of Korea", "KR", "KOR"},
    {"Kuwait", "The State of Kuwait", "KW", "KWT"},
    {"Kyrgyzstan", "The Kyrgyz Republic", "KG", "KGZ"},
    {
        "Laos",
        "Lao People's Democratic Republic",
        "The Lao People's Democratic Republic",
        "LA",
        "LAO",
    },
    {"Latvia", "The Republic of Latvia", "LV", "LVA"},
    {"Lebanon", "The Lebanese Republic", "LB", "LBN"},
    {"Lesotho", "The Kingdom of Lesotho", "LS", "LSO"},
    {"Liberia", "The Republic of Liberia", "LR", "LBR"},
    {"Libya", "The State of Libya", "LY", "LBY"},
    {"Liechtenstein", "The Principality of Liechtenstein", "LI", "LIE"},
    {"Lithuania", "The Republic of Lithuania", "LT", "LTU"},
    {"Luxembourg", "The Grand Duchy of Luxembourg", "LU", "LUX"},
    {"Macao", "Macao Special Administrative Region of China", "MO", "MAC"},
    {"North Macedonia", "The Republic of North Macedonia", "MK", "MKD"},
    {"Madagascar", "The Republic of Madagascar", "MG", "MDG"},
    {"Malawi", "The Republic of Malawi", "MW", "MWI"},
    {"Malaysia", "Malaysia", "MY", "MYS"},
    {"Maldives", "The Republic of Maldives", "MV", "MDV"},
    {"Mali", "The Republic of Mali", "ML", "MLI"},
    {"Malta", "The Republic of Malta", "MT", "MLT"},
    {
        "Marshall Islands",
        "The Marshall Islands",
        "The Republic of the Marshall Islands",
        "MH",
        "MHL",
    },
    {"Martinique", "Martinique", "MQ", "MTQ"},
    {"Mauritania", "The Islamic Republic of Mauritania", "MR", "MRT"},
    {"Mauritius", "The Republic of Mauritius", "MU", "MUS"},
    {"Mayotte", "The Department of Mayotte", "YT", "MYT"},
    {"Mexico", "The United Mexican States", "MX", "MEX"},
    {
        "Micronesia",
        "The Federated States of Micronesia",
        "FM",
        "FSM",
    },
    {"Moldova", "The Republic of Moldova", "MD", "MDA"},
    {"Monaco", "The Principality of Monaco", "MC", "MCO"},
    {"Mongolia", "The State of Mongolia", "MN", "MNG"},
    {"Montenegro", "Montenegro", "ME", "MNE"},
    {"Montserrat", "Montserrat", "MS", "MSR"},
    {"Morocco", "The Kingdom of Morocco", "MA", "MAR"},
    {"Mozambique", "The Republic of Mozambique", "MZ", "MOZ"},
    {"Myanmar", "The Republic of the Union of Myanmar", "MM", "MMR"},
    {"Namibia", "The Republic of Namibia", "NA", "NAM"},
    {"Nauru", "The Republic of Nauru", "NR", "NRU"},
    {"Nepal", "The Federal Democratic Republic of Nepal", "NP", "NPL"},
    {"Netherlands", "The Netherlands", "The Kingdom of the Netherlands", "NL", "NLD"},
    {"New Caledonia", "New Caledonia", "NC", "NCL"},
    {"New Zealand", "New Zealand", "NZ", "NZL"},
    {"Nicaragua", "The Republic of Nicaragua", "NI", "NIC"},
    {"Niger", "The Niger", "The Republic of the Niger", "NE", "NER"},
    {"Nigeria", "The Federal Republic of Nigeria", "NG", "NGA"},
    {"Niue", "NU", "NIU"},
    {"Norfolk Island", "The Territory of Norfolk Island", "NF", "NFK"},
    {
        "Northern Mariana Islands",
        "The Northern Mariana Islands",
        "The Commonwealth of the Northern Mariana Islands",
        "MP",
        "MNP",
    },
    {"Norway", "The Kingdom of Norway", "NO", "NOR"},
    {"Oman", "The Sultanate of Oman", "OM", "OMN"},
    {"Pakistan", "The Islamic Republic of Pakistan", "PK", "PAK"},
    {"Palau", "The Republic of Palau", "PW", "PLW"},
    {"Palestine", "The State of Palestine", "PS", "PSE"},
    {"Panama", "The Republic of Panamá", "PA", "PAN"},
    {"Papua New Guinea", "The Independent State of Papua New Guinea", "PG", "PNG"},
    {"Paraguay", "The Republic of Paraguay", "PY", "PRY"},
    {"Peru", "The Republic of Perú", "PE", "PER"},
    {"Philippines", "The Philippines", "The Republic of the Philippines", "PH", "PHL"},
    {"Pitcairn", "The Pitcairn, Henderson, Ducie and Oeno Islands", "PN", "PCN"},
    {"Poland", "The Republic of Poland", "PL", "POL"},
    {"Portugal", "The Portuguese Republic", "PT", "PRT"},
    {"Puerto Rico", "The Commonwealth of Puerto Rico", "PR", "PRI"},
    {"Qatar", "The State of Qatar", "QA", "QAT"},
    {"Reunion", "Réunion", "RE", "REU"},
    {"Romania", "RO", "ROU"},
    {"Russian Federation", "The Russian Federation", "RU", "RUS"},
    {"Rwanda", "The Republic of Rwanda", "RW", "RWA"},
    {"Saint Barthélemy", "The Collectivity of Saint-Barthélemy", "BL", "BLM"},
    {
        "Saint Helena, Ascension and Tristan da Cunha",
        "SH",
        "SHN",
    },
    {"Saint Kitts and Nevis", "Saint Kitts and Nevis", "KN", "KNA"},
    {"Saint Lucia", "Saint Lucia", "LC", "LCA"},
    {
        "Saint Martin (French part)",
        "Saint Martin",
        "The Collectivity of Saint-Martin",
        "MF",
        "MAF",
    },
    {
        "Saint Pierre and Miquelon",
        "The Overseas Collectivity of Saint-Pierre and Miquelon",
        "PM",
        "SPM",
    },
    {
        "Saint Vincent and the Grenadines",
        "Saint Vincent and the Grenadines",
        "VC",
        "VCT",
    },
    {"Samoa", "The Independent State of Samoa", "WS", "WSM"},
    {"San Marino", "The Republic of San Marino", "SM", "SMR"},
    {
        "Sao Tome and Principe",
        "The Democratic Republic of São Tomé and Príncipe",
        "ST",
        "STP",
    },
    {"Saudi Arabia", "The Kingdom of Saudi Arabia", "SA", "SAU"},
    {"Senegal", "The Republic of Senegal", "SN", "SEN"},
    {"Serbia", "The Republic of Serbia", "RS", "SRB"},
    {"Seychelles", "The Republic of Seychelles", "SC", "SYC"},
    {"Sierra Leone", "The Republic of Sierra Leone", "SL", "SLE"},
    {"Singapore", "The Republic of Singapore", "SG", "SGP"},
    {"Sint Maarten (Dutch part)", "Sint Maarten", "SX", "SXM"},
    {"Slovakia", "The Slovak Republic", "SK", "SVK"},
    {"Slovenia", "The Republic of Slovenia", "SI", "SVN"},
    {"Solomon Islands", "The Solomon Islands", "SB", "SLB"},
    {"Somalia", "The Federal Republic of Somalia", "SO", "SOM"},
    {"South Africa", "The Republic of South Africa", "ZA", "ZAF"},
    {
        "South Georgia and the South Sandwich Islands",
        "GS",
        "SGS",
    },
    {"South Sudan", "The Republic of South Sudan", "SS", "SSD"},
    {"Spain", "The Kingdom of Spain", "ES", "ESP"},
    {"Sri Lanka", "The Democratic Socialist Republic of Sri Lanka", "LK", "LKA"},
    {"Sudan", "The Republic of the Sudan", "SD", "SDN"},
    {"Suriname", "The Republic of Suriname", "SR", "SUR"},
    {"SvalbardJan Mayen", "Svalbard and Jan Mayen", "SJ", "SJM"},
    {"Sweden", "The Kingdom of Sweden", "SE", "SWE"},
    {"Switzerland", "The Swiss Confederation", "CH", "CHE"},
    {"Syrian Arab Republic", "The Syrian Arab Republic", "SY", "SYR"},
    {"Taiwan", "The Republic of China", "TW", "TWN"},
    {"Tajikistan", "The Republic of Tajikistan", "TJ", "TJK"},
    {
        "Tanzania",
        "Tanzania, the United Republic of",
        "The United Republic of Tanzania",
        "TZ",
        "TZA",
    },
    {"Thailand", "The Kingdom of Thailand", "TH", "THA"},
    {"Timor-Leste", "The Democratic Republic of Timor-Leste", "TL", "TLS"},
    {"Togo", "The Togolese Republic", "TG", "TGO"},
    {"Tokelau", "Tokelau", "TK", "TKL"},
    {"Tonga", "The Kingdom of Tonga", "TO", "TON"},
    {"Trinidad and Tobago", "The Republic of Trinidad and Tobago", "TT", "TTO"},
    {"Tunisia", "The Republic of Tunisia", "TN", "TUN"},
    {"Turkey", "The Republic of Turkey", "TR", "TUR"},
    {"Turkmenistan", "Turkmenistan", "TM", "TKM"},
    {"Turks and Caicos Islands", "The Turks and Caicos Islands", "TC", "TCA"},
    {"Tuvalu", "Tuvalu", "TV", "TUV"},
    {"Uganda", "The Republic of Uganda", "UG", "UGA"},
    {"Ukraine", "Ukraine", "UA", "UKR"},
    {"United Arab Emirates", "The United Arab Emirates", "AE", "ARE"},
    {
        "United Kingdom of Great Britain and Northern Ireland",
        "The United Kingdom of Great Britain and Northern Ireland",
        "United Kingdom",
        "UK",
        "GB",
        "GBR",
    },
    {
        "United States Minor Outlying Islands",
        "the United States Minor Outlying Islands",
        "UM",
        "UMI",
    },
    {"United States of America", "The United States of America", "US", "USA"},
    {"Uruguay", "The Oriental Republic of Uruguay", "UY", "URY"},
    {"Uzbekistan", "The Republic of Uzbekistan", "UZ", "UZB"},
    {"Vanuatu", "The Republic of Vanuatu", "VU", "VUT"},
    {
        "Venezuela",
        "The Bolivarian Republic of Venezuela",
        "VE",
        "VEN",
    },
    {"Viet Nam", "The Socialist Republic of Viet Nam", "VN", "VNM"},
    {"Virgin Islands", "Virgin Islands (British)", "The Virgin Islands", "VG", "VGB"},
    {
        "Virgin Islands",
        "Virgin Islands (U.S.)",
        "The Virgin Islands of the United States",
        "VI",
        "VIR",
    },
    {
        "Wallis and Futuna",
        "The Territory of the Wallis and Futuna Islands",
        "WF",
        "WLF",
    },
    {"Western Sahara", "The Sahrawi Arab Democratic Republic", "EH", "ESH"},
    {"Yemen", "The Republic of Yemen", "YE", "YEM"},
    {"Zambia", "The Republic of Zambia", "ZM", "ZMB"},
    {"Zimbabwe", "The Republic of Zimbabwe", "ZW", "ZWE"},
]


def _get_country_mappings():
    mapping = collections.defaultdict(list)
    for i, country_names in enumerate(COUNTRIES):
        for country_name in country_names:
            mapping[unidecode.unidecode(country_name.lower())].append(i)

    return mapping


COUNTRY_MAPPING = _get_country_mappings()
