# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import company_name.organization_name_agent_pb2 as organization__name__agent__pb2


class OrganizationNameAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompareOrganizationNames = channel.unary_unary(
            "/silenteight.agent.organizationname.v1.api.OrganizationNameAgent/CompareOrganizationNames",
            request_serializer=organization__name__agent__pb2.CompareOrganizationNamesRequest.SerializeToString,
            response_deserializer=organization__name__agent__pb2.CompareOrganizationNamesResponse.FromString,
        )


class OrganizationNameAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompareOrganizationNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OrganizationNameAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CompareOrganizationNames": grpc.unary_unary_rpc_method_handler(
            servicer.CompareOrganizationNames,
            request_deserializer=organization__name__agent__pb2.CompareOrganizationNamesRequest.FromString,
            response_serializer=organization__name__agent__pb2.CompareOrganizationNamesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "silenteight.agent.organizationname.v1.api.OrganizationNameAgent", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class OrganizationNameAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompareOrganizationNames(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silenteight.agent.organizationname.v1.api.OrganizationNameAgent/CompareOrganizationNames",
            organization__name__agent__pb2.CompareOrganizationNamesRequest.SerializeToString,
            organization__name__agent__pb2.CompareOrganizationNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
