/*
 * HSCB-Bridge-batch API
 * HSCB-Bridge-batch API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.model.rest.input;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets ChangeType
 */
@JsonAdapter(ChangeType.Adapter.class)
public enum ChangeType {
  MINOR("MINOR"),
  MAJOR("MAJOR");

  private String value;

  ChangeType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ChangeType fromValue(String text) {
    for (ChangeType b : ChangeType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ChangeType> {

    @Override
    public void write(final JsonWriter jsonWriter, final ChangeType enumeration) throws
        IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ChangeType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ChangeType.fromValue(String.valueOf(value));
    }
  }
}
