###
// 2021-10-01_1837_osama_bin_laden.json
POST http://localhost:24602/rest/pb/alert
Content-Type: application/json

< ../svb-examples/2021-10-01_1837_osama_bin_laden.json

###
// 2021-10-04-1851_saddam_hussain.json
POST http://localhost:24602/rest/pb/alert
Content-Type: application/json

< ../svb-examples/2021-10-04-1851_saddam_hussain.json

###
// 2021_10_08-1754_uat_firco_alert.json
POST http://localhost:24602/rest/pb/alert
Content-Type: application/json

< ../svb-examples/2021_10_08-1754_uat_firco_alert.json
