# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etl_learning.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="etl_learning.proto",
    package="silenteight.datascience.etllearning.v1.api",
    syntax="proto3",
    serialized_options=b"\n.com.silenteight.datascience.etllearning.v1.apiB\023EtlLearningApiProtoP\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x12\x65tl_learning.proto\x12*silenteight.datascience.etllearning.v1.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto"p\n\x15RunEtlLearningRequest\x12W\n\x0flearning_alerts\x18\x01 \x03(\x0b\x32\x39.silenteight.datascience.etllearning.v1.api.LearningAlertB\x03\xe0\x41\x02"\xd6\x02\n\rLearningAlert\x12\x15\n\x08\x62\x61tch_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\nalert_name\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12X\n\x10learning_matches\x18\x03 \x03(\x0b\x32\x39.silenteight.datascience.etllearning.v1.api.LearningMatchB\x03\xe0\x41\x02\x12\x65\n\x0c\x66lat_payload\x18\x04 \x03(\x0b\x32J.silenteight.datascience.etllearning.v1.api.LearningAlert.FlatPayloadEntryB\x03\xe0\x41\x02\x12 \n\x13\x61lert_event_history\x18\x05 \x01(\tB\x03\xe0\x41\x02\x1a\x32\n\x10\x46latPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"?\n\rLearningMatch\x12\x15\n\x08match_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\nmatch_name\x18\x02 \x01(\tB\x03\xe0\x41\x02"o\n\x16RunEtlLearningResponse\x12U\n\netl_alerts\x18\x01 \x03(\x0b\x32<.silenteight.datascience.etllearning.v1.api.EtlLearningAlertB\x03\xe0\x41\x02"\x90\x01\n\x10\x45tlLearningAlert\x12\x15\n\x08\x62\x61tch_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x15\n\x08\x61lert_id\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12N\n\netl_status\x18\x03 \x01(\x0e\x32\x35.silenteight.datascience.etllearning.v1.api.EtlStatusB\x03\xe0\x41\x02*%\n\tEtlStatus\x12\x0b\n\x07\x46\x41ILURE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x32\xde\x01\n\x12\x45tlLearningService\x12\xc7\x01\n\x0eRunEtlLearning\x12\x41.silenteight.datascience.etllearning.v1.api.RunEtlLearningRequest\x1a\x42.silenteight.datascience.etllearning.v1.api.RunEtlLearningResponse".\x82\xd3\xe4\x93\x02("\x16/v1/etl:runEtlLearning:\x0erunEtlLearningBG\n.com.silenteight.datascience.etllearning.v1.apiB\x13\x45tlLearningApiProtoP\x01\x62\x06proto3',
    dependencies=[
        google_dot_api_dot_annotations__pb2.DESCRIPTOR,
        google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,
    ],
)

_ETLSTATUS = _descriptor.EnumDescriptor(
    name="EtlStatus",
    full_name="silenteight.datascience.etllearning.v1.api.EtlStatus",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="FAILURE",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SUCCESS",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=913,
    serialized_end=950,
)
_sym_db.RegisterEnumDescriptor(_ETLSTATUS)

EtlStatus = enum_type_wrapper.EnumTypeWrapper(_ETLSTATUS)
FAILURE = 0
SUCCESS = 1


_RUNETLLEARNINGREQUEST = _descriptor.Descriptor(
    name="RunEtlLearningRequest",
    full_name="silenteight.datascience.etllearning.v1.api.RunEtlLearningRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="learning_alerts",
            full_name="silenteight.datascience.etllearning.v1.api.RunEtlLearningRequest.learning_alerts",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=129,
    serialized_end=241,
)


_LEARNINGALERT_FLATPAYLOADENTRY = _descriptor.Descriptor(
    name="FlatPayloadEntry",
    full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.FlatPayloadEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.FlatPayloadEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.FlatPayloadEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=536,
    serialized_end=586,
)

_LEARNINGALERT = _descriptor.Descriptor(
    name="LearningAlert",
    full_name="silenteight.datascience.etllearning.v1.api.LearningAlert",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="batch_id",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.batch_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="alert_name",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.alert_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="learning_matches",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.learning_matches",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="flat_payload",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.flat_payload",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="alert_event_history",
            full_name="silenteight.datascience.etllearning.v1.api.LearningAlert.alert_event_history",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _LEARNINGALERT_FLATPAYLOADENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=244,
    serialized_end=586,
)


_LEARNINGMATCH = _descriptor.Descriptor(
    name="LearningMatch",
    full_name="silenteight.datascience.etllearning.v1.api.LearningMatch",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="match_id",
            full_name="silenteight.datascience.etllearning.v1.api.LearningMatch.match_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="match_name",
            full_name="silenteight.datascience.etllearning.v1.api.LearningMatch.match_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=588,
    serialized_end=651,
)


_RUNETLLEARNINGRESPONSE = _descriptor.Descriptor(
    name="RunEtlLearningResponse",
    full_name="silenteight.datascience.etllearning.v1.api.RunEtlLearningResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="etl_alerts",
            full_name="silenteight.datascience.etllearning.v1.api.RunEtlLearningResponse.etl_alerts",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=653,
    serialized_end=764,
)


_ETLLEARNINGALERT = _descriptor.Descriptor(
    name="EtlLearningAlert",
    full_name="silenteight.datascience.etllearning.v1.api.EtlLearningAlert",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="batch_id",
            full_name="silenteight.datascience.etllearning.v1.api.EtlLearningAlert.batch_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="alert_id",
            full_name="silenteight.datascience.etllearning.v1.api.EtlLearningAlert.alert_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="etl_status",
            full_name="silenteight.datascience.etllearning.v1.api.EtlLearningAlert.etl_status",
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=767,
    serialized_end=911,
)

_RUNETLLEARNINGREQUEST.fields_by_name["learning_alerts"].message_type = _LEARNINGALERT
_LEARNINGALERT_FLATPAYLOADENTRY.containing_type = _LEARNINGALERT
_LEARNINGALERT.fields_by_name["learning_matches"].message_type = _LEARNINGMATCH
_LEARNINGALERT.fields_by_name["flat_payload"].message_type = _LEARNINGALERT_FLATPAYLOADENTRY
_RUNETLLEARNINGRESPONSE.fields_by_name["etl_alerts"].message_type = _ETLLEARNINGALERT
_ETLLEARNINGALERT.fields_by_name["etl_status"].enum_type = _ETLSTATUS
DESCRIPTOR.message_types_by_name["RunEtlLearningRequest"] = _RUNETLLEARNINGREQUEST
DESCRIPTOR.message_types_by_name["LearningAlert"] = _LEARNINGALERT
DESCRIPTOR.message_types_by_name["LearningMatch"] = _LEARNINGMATCH
DESCRIPTOR.message_types_by_name["RunEtlLearningResponse"] = _RUNETLLEARNINGRESPONSE
DESCRIPTOR.message_types_by_name["EtlLearningAlert"] = _ETLLEARNINGALERT
DESCRIPTOR.enum_types_by_name["EtlStatus"] = _ETLSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunEtlLearningRequest = _reflection.GeneratedProtocolMessageType(
    "RunEtlLearningRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RUNETLLEARNINGREQUEST,
        "__module__": "etl_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etllearning.v1.api.RunEtlLearningRequest)
    },
)
_sym_db.RegisterMessage(RunEtlLearningRequest)

LearningAlert = _reflection.GeneratedProtocolMessageType(
    "LearningAlert",
    (_message.Message,),
    {
        "FlatPayloadEntry": _reflection.GeneratedProtocolMessageType(
            "FlatPayloadEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _LEARNINGALERT_FLATPAYLOADENTRY,
                "__module__": "etl_learning_pb2"
                # @@protoc_insertion_point(class_scope:silenteight.datascience.etllearning.v1.api.LearningAlert.FlatPayloadEntry)
            },
        ),
        "DESCRIPTOR": _LEARNINGALERT,
        "__module__": "etl_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etllearning.v1.api.LearningAlert)
    },
)
_sym_db.RegisterMessage(LearningAlert)
_sym_db.RegisterMessage(LearningAlert.FlatPayloadEntry)

LearningMatch = _reflection.GeneratedProtocolMessageType(
    "LearningMatch",
    (_message.Message,),
    {
        "DESCRIPTOR": _LEARNINGMATCH,
        "__module__": "etl_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etllearning.v1.api.LearningMatch)
    },
)
_sym_db.RegisterMessage(LearningMatch)

RunEtlLearningResponse = _reflection.GeneratedProtocolMessageType(
    "RunEtlLearningResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _RUNETLLEARNINGRESPONSE,
        "__module__": "etl_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etllearning.v1.api.RunEtlLearningResponse)
    },
)
_sym_db.RegisterMessage(RunEtlLearningResponse)

EtlLearningAlert = _reflection.GeneratedProtocolMessageType(
    "EtlLearningAlert",
    (_message.Message,),
    {
        "DESCRIPTOR": _ETLLEARNINGALERT,
        "__module__": "etl_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.datascience.etllearning.v1.api.EtlLearningAlert)
    },
)
_sym_db.RegisterMessage(EtlLearningAlert)


DESCRIPTOR._options = None
_RUNETLLEARNINGREQUEST.fields_by_name["learning_alerts"]._options = None
_LEARNINGALERT_FLATPAYLOADENTRY._options = None
_LEARNINGALERT.fields_by_name["batch_id"]._options = None
_LEARNINGALERT.fields_by_name["alert_name"]._options = None
_LEARNINGALERT.fields_by_name["learning_matches"]._options = None
_LEARNINGALERT.fields_by_name["flat_payload"]._options = None
_LEARNINGALERT.fields_by_name["alert_event_history"]._options = None
_LEARNINGMATCH.fields_by_name["match_id"]._options = None
_LEARNINGMATCH.fields_by_name["match_name"]._options = None
_RUNETLLEARNINGRESPONSE.fields_by_name["etl_alerts"]._options = None
_ETLLEARNINGALERT.fields_by_name["batch_id"]._options = None
_ETLLEARNINGALERT.fields_by_name["alert_id"]._options = None
_ETLLEARNINGALERT.fields_by_name["etl_status"]._options = None

_ETLLEARNINGSERVICE = _descriptor.ServiceDescriptor(
    name="EtlLearningService",
    full_name="silenteight.datascience.etllearning.v1.api.EtlLearningService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=953,
    serialized_end=1175,
    methods=[
        _descriptor.MethodDescriptor(
            name="RunEtlLearning",
            full_name="silenteight.datascience.etllearning.v1.api.EtlLearningService.RunEtlLearning",
            index=0,
            containing_service=None,
            input_type=_RUNETLLEARNINGREQUEST,
            output_type=_RUNETLLEARNINGRESPONSE,
            serialized_options=b'\202\323\344\223\002("\026/v1/etl:runEtlLearning:\016runEtlLearning',
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ETLLEARNINGSERVICE)

DESCRIPTOR.services_by_name["EtlLearningService"] = _ETLLEARNINGSERVICE

# @@protoc_insertion_point(module_scope)
