# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: historical_decision_learning.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2

import etl_pipeline.learning.proto.common_pb2 as common__pb2
from etl_pipeline.learning.proto.common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
    name="historical_decision_learning.proto",
    package="silenteight.learningstore.historicaldecision.v2.api",
    syntax="proto3",
    serialized_options=b"\n=com.silenteight.proto.learningstore.historicaldecision.v2.apiB,HistoricalDecisionLearningStoreExchangeProtoP\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n"historical_decision_learning.proto\x12\x33silenteight.learningstore.historicaldecision.v2.api\x1a\x1fgoogle/api/field_behavior.proto\x1a\x0c\x63ommon.proto"\x81\x01\n.HistoricalDecisionLearningStoreExchangeRequest\x12O\n\x06\x61lerts\x18\x01 \x03(\x0b\x32:.silenteight.learningstore.historicaldecision.v2.api.AlertB\x03\xe0\x41\x02"\xa4\x03\n\x05\x41lert\x12\x15\n\x08\x61lert_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x15\n\x08match_id\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12V\n\twatchlist\x18\x03 \x01(\x0b\x32>.silenteight.learningstore.historicaldecision.v2.api.WatchlistB\x03\xe0\x41\x02\x12]\n\ralerted_party\x18\x04 \x01(\x0b\x32\x41.silenteight.learningstore.historicaldecision.v2.api.AlertedPartyB\x03\xe0\x41\x02\x12U\n\tdecisions\x18\x05 \x03(\x0b\x32=.silenteight.learningstore.historicaldecision.v2.api.DecisionB\x03\xe0\x41\x02\x12_\n\x0e\x64iscriminators\x18\x06 \x03(\x0b\x32\x42.silenteight.learningstore.historicaldecision.v2.api.DiscriminatorB\x03\xe0\x41\x02"5\n\x0c\x41lertedParty\x12\x0f\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x14\n\x07\x63ountry\x18\x02 \x01(\tB\x03\xe0\x41\x01\x42o\n=com.silenteight.proto.learningstore.historicaldecision.v2.apiB,HistoricalDecisionLearningStoreExchangeProtoP\x01P\x01\x62\x06proto3',
    dependencies=[
        google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,
        common__pb2.DESCRIPTOR,
    ],
    public_dependencies=[
        common__pb2.DESCRIPTOR,
    ],
)


_HISTORICALDECISIONLEARNINGSTOREEXCHANGEREQUEST = _descriptor.Descriptor(
    name="HistoricalDecisionLearningStoreExchangeRequest",
    full_name="silenteight.learningstore.historicaldecision.v2.api.HistoricalDecisionLearningStoreExchangeRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="alerts",
            full_name="silenteight.learningstore.historicaldecision.v2.api.HistoricalDecisionLearningStoreExchangeRequest.alerts",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=139,
    serialized_end=268,
)


_ALERT = _descriptor.Descriptor(
    name="Alert",
    full_name="silenteight.learningstore.historicaldecision.v2.api.Alert",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="alert_id",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Alert.alert_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="match_id",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Alert.match_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="watchlist",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Alert.watchlist",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="alerted_party",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Alert.alerted_party",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="decisions",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Alert.decisions",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="discriminators",
            full_name="silenteight.learningstore.historicaldecision.v2.api.Alert.discriminators",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=271,
    serialized_end=691,
)


_ALERTEDPARTY = _descriptor.Descriptor(
    name="AlertedParty",
    full_name="silenteight.learningstore.historicaldecision.v2.api.AlertedParty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="silenteight.learningstore.historicaldecision.v2.api.AlertedParty.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\002",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="country",
            full_name="silenteight.learningstore.historicaldecision.v2.api.AlertedParty.country",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\340A\001",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=693,
    serialized_end=746,
)

_HISTORICALDECISIONLEARNINGSTOREEXCHANGEREQUEST.fields_by_name["alerts"].message_type = _ALERT
_ALERT.fields_by_name["watchlist"].message_type = common__pb2._WATCHLIST
_ALERT.fields_by_name["alerted_party"].message_type = _ALERTEDPARTY
_ALERT.fields_by_name["decisions"].message_type = common__pb2._DECISION
_ALERT.fields_by_name["discriminators"].message_type = common__pb2._DISCRIMINATOR
DESCRIPTOR.message_types_by_name[
    "HistoricalDecisionLearningStoreExchangeRequest"
] = _HISTORICALDECISIONLEARNINGSTOREEXCHANGEREQUEST
DESCRIPTOR.message_types_by_name["Alert"] = _ALERT
DESCRIPTOR.message_types_by_name["AlertedParty"] = _ALERTEDPARTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HistoricalDecisionLearningStoreExchangeRequest = _reflection.GeneratedProtocolMessageType(
    "HistoricalDecisionLearningStoreExchangeRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _HISTORICALDECISIONLEARNINGSTOREEXCHANGEREQUEST,
        "__module__": "historical_decision_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.learningstore.historicaldecision.v2.api.HistoricalDecisionLearningStoreExchangeRequest)
    },
)
_sym_db.RegisterMessage(HistoricalDecisionLearningStoreExchangeRequest)

Alert = _reflection.GeneratedProtocolMessageType(
    "Alert",
    (_message.Message,),
    {
        "DESCRIPTOR": _ALERT,
        "__module__": "historical_decision_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.learningstore.historicaldecision.v2.api.Alert)
    },
)
_sym_db.RegisterMessage(Alert)

AlertedParty = _reflection.GeneratedProtocolMessageType(
    "AlertedParty",
    (_message.Message,),
    {
        "DESCRIPTOR": _ALERTEDPARTY,
        "__module__": "historical_decision_learning_pb2"
        # @@protoc_insertion_point(class_scope:silenteight.learningstore.historicaldecision.v2.api.AlertedParty)
    },
)
_sym_db.RegisterMessage(AlertedParty)


DESCRIPTOR._options = None
_HISTORICALDECISIONLEARNINGSTOREEXCHANGEREQUEST.fields_by_name["alerts"]._options = None
_ALERT.fields_by_name["alert_id"]._options = None
_ALERT.fields_by_name["match_id"]._options = None
_ALERT.fields_by_name["watchlist"]._options = None
_ALERT.fields_by_name["alerted_party"]._options = None
_ALERT.fields_by_name["decisions"]._options = None
_ALERT.fields_by_name["discriminators"]._options = None
_ALERTEDPARTY.fields_by_name["id"]._options = None
_ALERTEDPARTY.fields_by_name["country"]._options = None
# @@protoc_insertion_point(module_scope)
