/*
 * HSCB-Bridge-batch API
 * HSCB-Bridge-batch API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets BatchAlertItemStatus
 */
@JsonAdapter(BatchAlertItemStatus.Adapter.class)
public enum BatchAlertItemStatus {
  PROCESSING("PROCESSING"),
  ERROR("ERROR"),
  COMPLETED("COMPLETED"),
  STORED("STORED");

  private String value;

  BatchAlertItemStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BatchAlertItemStatus fromValue(String text) {
    for (BatchAlertItemStatus b : BatchAlertItemStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<BatchAlertItemStatus> {

    @Override
    public void write(final JsonWriter jsonWriter, final BatchAlertItemStatus enumeration) throws
        IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BatchAlertItemStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return BatchAlertItemStatus.fromValue(String.valueOf(value));
    }
  }
}
