/*
 * HSCB-Bridge-batch API
 * HSCB-Bridge-batch API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets BatchStatus
 */
@JsonAdapter(BatchStatus.Adapter.class)
public enum BatchStatus {
  PROCESSING("PROCESSING"),
  ERROR("ERROR"),
  COMPLETED("COMPLETED"),
  DELIVERED("DELIVERED"),
  CANCELLED("CANCELLED"),
  STORED("STORED");

  private String value;

  BatchStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BatchStatus fromValue(String text) {
    for (BatchStatus b : BatchStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<BatchStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final BatchStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BatchStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return BatchStatus.fromValue(String.valueOf(value));
    }
  }
}
