/*
 * HSCB-Bridge-batch API
 * HSCB-Bridge-batch API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BatchSolvedAlertsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-02T11:57:31.043Z[GMT]")
public class BatchSolvedAlerts {

  @JsonProperty("batchId")
  @NotNull
  @NotBlank
  private String batchId = null;

  @JsonProperty("batchStatus")
  @NotNull
  private BatchStatus batchStatus = null;

  @JsonProperty("alerts")
  @NotNull
  @Size(min = 1)
  @Valid 
  private List<SolvedAlert> alerts = new ArrayList<>();

  @JsonProperty("errorAlerts")
  @Valid
  private List<ErrorAlert> errorAlerts = new ArrayList<>();

  public BatchSolvedAlerts batchId(String batchId) {
    this.batchId = batchId;
    return this;
  }

  /**
   * Get batchId
   * @return batchId
   **/
  @Schema(description = "")
  public String getBatchId() {
    return batchId;
  }

  public void setBatchId(String batchId) {
    this.batchId = batchId;
  }

  public BatchSolvedAlerts batchStatus(BatchStatus batchStatus) {
    this.batchStatus = batchStatus;
    return this;
  }

  /**
   * Get batchStatus
   * @return batchStatus
   **/
  @Schema(description = "")
  public BatchStatus getBatchStatus() {
    return batchStatus;
  }

  public void setBatchStatus(BatchStatus batchStatus) {
    this.batchStatus = batchStatus;
  }

  public BatchSolvedAlerts alerts(List<SolvedAlert> alerts) {
    this.alerts = alerts;
    return this;
  }

  public BatchSolvedAlerts addAlertsItem(SolvedAlert alertsItem) {
    if (this.alerts == null) {
      this.alerts = new ArrayList<SolvedAlert>();
    }
    this.alerts.add(alertsItem);
    return this;
  }

  /**
   * Get alerts
   * @return alerts
   **/
  @Schema(description = "")
  public List<SolvedAlert> getAlerts() {
    return alerts;
  }

  public void setAlerts(List<SolvedAlert> alerts) {
    this.alerts = alerts;
  }

  public BatchSolvedAlerts errorAlerts(List<ErrorAlert> errorAlerts) {
    this.errorAlerts = errorAlerts;
    return this;
  }

  public BatchSolvedAlerts addErrorAlertsItem(ErrorAlert alertsItem) {
    if (this.errorAlerts == null) {
      this.errorAlerts = new ArrayList<ErrorAlert>();
    }
    this.errorAlerts.add(alertsItem);
    return this;
  }

  @Schema(description = "")
  public List<ErrorAlert> getErrorAlerts() {
    return errorAlerts;
  }

  public void setErrorAlerts(List<ErrorAlert> errorAlerts) {
    this.errorAlerts = errorAlerts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchSolvedAlerts batchSolvedAlerts = (BatchSolvedAlerts) o;
    return Objects.equals(this.batchId, batchSolvedAlerts.batchId) &&
        Objects.equals(this.batchStatus, batchSolvedAlerts.batchStatus) &&
        Objects.equals(this.alerts, batchSolvedAlerts.alerts) &&
        Objects.equals(this.errorAlerts, batchSolvedAlerts.errorAlerts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchId, batchStatus, alerts, errorAlerts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchSolvedAlertsResponse {\n");

    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    batchStatus: ").append(toIndentedString(batchStatus)).append("\n");
    sb.append("    alerts: ").append(toIndentedString(alerts)).append("\n");
    sb.append("    errorAlerts: ").append(toIndentedString(errorAlerts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
