/*
 * HSCB-Bridge-bulk API
 * HSCB-Bridge-bulk API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.validation.annotation.Validated;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BulkSolvedAlertsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-02T11:57:31.043Z[GMT]")
@Validated
public class BulkSolvedAlerts {
  @SerializedName("bulkId")
  private String bulkId = null;

  @SerializedName("bulkStatus")
  private BulkStatus bulkStatus = null;

  @SerializedName("alerts")
  @NotNull
  @Size(min = 1)
  private List<SolvedAlert> alerts = null;

  public BulkSolvedAlerts bulkId(String bulkId) {
    this.bulkId = bulkId;
    return this;
  }

   /**
   * Get bulkId
   * @return bulkId
  **/
  @Schema(description = "")
  public String getBulkId() {
    return bulkId;
  }

  public void setBulkId(String bulkId) {
    this.bulkId = bulkId;
  }

  public BulkSolvedAlerts bulkStatus(BulkStatus bulkStatus) {
    this.bulkStatus = bulkStatus;
    return this;
  }

   /**
   * Get bulkStatus
   * @return bulkStatus
  **/
  @Schema(description = "")
  public BulkStatus getBulkStatus() {
    return bulkStatus;
  }

  public void setBulkStatus(BulkStatus bulkStatus) {
    this.bulkStatus = bulkStatus;
  }

  public BulkSolvedAlerts alerts(List<SolvedAlert> alerts) {
    this.alerts = alerts;
    return this;
  }

  public BulkSolvedAlerts addAlertsItem(SolvedAlert alertsItem) {
    if (this.alerts == null) {
      this.alerts = new ArrayList<SolvedAlert>();
    }
    this.alerts.add(alertsItem);
    return this;
  }

   /**
   * Get alerts
   * @return alerts
  **/
  @Schema(description = "")
  public List<SolvedAlert> getAlerts() {
    return alerts;
  }

  public void setAlerts(List<SolvedAlert> alerts) {
    this.alerts = alerts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkSolvedAlerts bulkSolvedAlerts = (BulkSolvedAlerts) o;
    return Objects.equals(this.bulkId, bulkSolvedAlerts.bulkId) &&
        Objects.equals(this.bulkStatus, bulkSolvedAlerts.bulkStatus) &&
        Objects.equals(this.alerts, bulkSolvedAlerts.alerts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkId, bulkStatus, alerts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkSolvedAlertsResponse {\n");

    sb.append("    bulkId: ").append(toIndentedString(bulkId)).append("\n");
    sb.append("    bulkStatus: ").append(toIndentedString(bulkStatus)).append("\n");
    sb.append("    alerts: ").append(toIndentedString(alerts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
