/*
 * HSCB-Bridge-bulk API
 * HSCB-Bridge-bulk API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * BulkStatusResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-02T11:57:31.043Z[GMT]")
public class BulkStatusResponse {
  @SerializedName("bulkId")
  private String bulkId = null;

  @SerializedName("bulkStatus")
  private BulkStatus bulkStatus = null;

  @SerializedName("policyName")
  private String policyName = null;

  @SerializedName("requestedAlerts")
  private List<BulkAlertItem> requestedAlerts = null;

  public BulkStatusResponse bulkId(String bulkId) {
    this.bulkId = bulkId;
    return this;
  }

   /**
   * Get bulkId
   * @return bulkId
  **/
  @Schema(description = "")
  public String getBulkId() {
    return bulkId;
  }

  public void setBulkId(String bulkId) {
    this.bulkId = bulkId;
  }

  public BulkStatusResponse bulkStatus(BulkStatus bulkStatus) {
    this.bulkStatus = bulkStatus;
    return this;
  }

   /**
   * Get bulkStatus
   * @return bulkStatus
  **/
  @Schema(description = "")
  public BulkStatus getBulkStatus() {
    return bulkStatus;
  }

  public void setBulkStatus(BulkStatus bulkStatus) {
    this.bulkStatus = bulkStatus;
  }

  public BulkStatusResponse policyName(String policyName) {
    this.policyName = policyName;
    return this;
  }

  /**
   * Get solvingModelName
   * @return solvingModelName
   **/
  @Schema(description = "")
  public String getPolicyName() {
    return policyName;
  }

  public void setPolicyName(String policyName) {
    this.policyName = policyName;
  }

  public BulkStatusResponse requestedAlerts(List<BulkAlertItem> requestedAlerts) {
    this.requestedAlerts = requestedAlerts;
    return this;
  }

  public BulkStatusResponse addRequestedAlertsItem(BulkAlertItem requestedAlertsItem) {
    if (this.requestedAlerts == null) {
      this.requestedAlerts = new ArrayList<BulkAlertItem>();
    }
    this.requestedAlerts.add(requestedAlertsItem);
    return this;
  }

   /**
   * Get requestedAlerts
   * @return requestedAlerts
  **/
  @Schema(description = "")
  public List<BulkAlertItem> getRequestedAlerts() {
    return requestedAlerts;
  }

  public void setRequestedAlerts(List<BulkAlertItem> requestedAlerts) {
    this.requestedAlerts = requestedAlerts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkStatusResponse bulkStatusResponse = (BulkStatusResponse) o;
    return Objects.equals(this.bulkId, bulkStatusResponse.bulkId) &&
        Objects.equals(this.bulkStatus, bulkStatusResponse.bulkStatus) &&
        Objects.equals(this.requestedAlerts, bulkStatusResponse.requestedAlerts) &&
        Objects.equals(this.policyName, bulkStatusResponse.policyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkId, bulkStatus, requestedAlerts, policyName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkStatusResponse {\n");
    
    sb.append("    bulkId: ").append(toIndentedString(bulkId)).append("\n");
    sb.append("    bulkStatus: ").append(toIndentedString(bulkStatus)).append("\n");
    sb.append("    requestedAlerts: ").append(toIndentedString(requestedAlerts)).append("\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
