/*
 * HSCB-Bridge-bulk API
 * HSCB-Bridge-bulk API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * BulkAcceptedResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-02T11:57:31.043Z[GMT]")
public class BulkAcceptedResponse {
  @SerializedName("bulkId")
  private String bulkId = null;

  public BulkAcceptedResponse bulkId(String bulkId) {
    this.bulkId = bulkId;
    return this;
  }

   /**
   * Get bulkId
   * @return bulkId
  **/
  @Schema(description = "")
  public String getBulkId() {
    return bulkId;
  }

  public void setBulkId(String bulkId) {
    this.bulkId = bulkId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkAcceptedResponse bulkAcceptedResponse = (BulkAcceptedResponse) o;
    return Objects.equals(this.bulkId, bulkAcceptedResponse.bulkId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkAcceptedResponse {\n");
    
    sb.append("    bulkId: ").append(toIndentedString(bulkId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
