/*
 * HSCB-Bridge-batch API
 * HSCB-Bridge-batch API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.silenteight.hsbc.bridge.bulk.rest;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 * SolvedAlert
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-16T08:18:56.492Z[GMT]")
public class SolvedAlert {

  @JsonProperty("id")
  @NotNull
  @NotBlank
  private String id = null;

  @JsonProperty("recommendation")
  @NotNull
  @NotBlank
  private String recommendation = null;

  @JsonProperty("comment")
  @NotNull
  @NotBlank
  private String comment = null;

  @JsonProperty("policy_id")
  @NotNull
  @NotBlank
  private String policyId = null;

  @JsonProperty("step_id")
  @NotNull
  @NotBlank
  private String stepId = null;

  @JsonProperty("fv_signature")
  @NotNull
  @NotBlank
  private String fvSignature = null;

  @JsonProperty("alertMetadata")
  @NotNull
  @Valid 
  private List<AlertMetadata> alertMetadata = null;

  public SolvedAlert id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SolvedAlert recommendation(String recommendation) {
    this.recommendation = recommendation;
    return this;
  }

  /**
   * Get recommendation
   *
   * @return recommendation
   **/
  @Schema(description = "")
  public String getRecommendation() {
    return recommendation;
  }

  public void setRecommendation(String recommendation) {
    this.recommendation = recommendation;
  }

  public SolvedAlert comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   *
   * @return comment
   **/
  @Schema(description = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public SolvedAlert policyId(String policyId) {
    this.policyId = policyId;
    return this;
  }

  /**
   * Get policyId
   *
   * @return policyId
   **/
  @Schema(description = "")
  public String getPolicyId() {
    return policyId;
  }

  public void setPolicyId(String policyId) {
    this.policyId = policyId;
  }

  public SolvedAlert stepId(String stepId) {
    this.stepId = stepId;
    return this;
  }

  /**
   * Get stepId
   *
   * @return stepId
   **/
  @Schema(description = "")
  public String getStepId() {
    return stepId;
  }

  public void setStepId(String stepId) {
    this.stepId = stepId;
  }

  public SolvedAlert fvSignature(String fvSignature) {
    this.fvSignature = fvSignature;
    return this;
  }

  /**
   * Get fvSignature
   *
   * @return fvSignature
   **/
  @Schema(description = "")
  public String getFvSignature() {
    return fvSignature;
  }

  public void setFvSignature(String fvSignature) {
    this.fvSignature = fvSignature;
  }

  public SolvedAlert alertMetadata(List<AlertMetadata> alertMetadata) {
    this.alertMetadata = alertMetadata;
    return this;
  }

  public SolvedAlert addAlertMetadataItem(AlertMetadata alertMetadataItem) {
    if (this.alertMetadata == null) {
      this.alertMetadata = new ArrayList<AlertMetadata>();
    }
    this.alertMetadata.add(alertMetadataItem);
    return this;
  }

  /**
   * Get alertMetadata
   *
   * @return alertMetadata
   **/
  @Schema(description = "")
  public List<AlertMetadata> getAlertMetadata() {
    return alertMetadata;
  }

  public void setAlertMetadata(List<AlertMetadata> alertMetadata) {
    this.alertMetadata = alertMetadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolvedAlert solvedAlert = (SolvedAlert) o;
    return Objects.equals(this.id, solvedAlert.id) &&
        Objects.equals(this.recommendation, solvedAlert.recommendation) &&
        Objects.equals(this.comment, solvedAlert.comment) &&
        Objects.equals(this.policyId, solvedAlert.policyId) &&
        Objects.equals(this.stepId, solvedAlert.stepId) &&
        Objects.equals(this.fvSignature, solvedAlert.fvSignature) &&
        Objects.equals(this.alertMetadata, solvedAlert.alertMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, recommendation, comment, policyId, stepId, fvSignature, alertMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolvedAlert {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    recommendation: ").append(toIndentedString(recommendation)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    stepId: ").append(toIndentedString(stepId)).append("\n");
    sb.append("    fvSignature: ").append(toIndentedString(fvSignature)).append("\n");
    sb.append("    alertMetadata: ").append(toIndentedString(alertMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
