
-- USER SQL
CREATE USER LC_GNS_WEB_SIT_01 IDENTIFIED BY "password"
DEFAULT TABLESPACE "LC_GNS_SIT_DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER LC_GNS_WEB_SIT_01 QUOTA UNLIMITED ON LC_GNS_SIT_DATA;

-- ROLES
GRANT CONNECT, RESOURCE TO LC_GNS_WEB_SIT_01;

-- SYSTEM PRIVILEGES
GRANT ALL PRIVILEGES TO LC_GNS_WEB_SIT_01;
