EXAMPLES = [
    (
        {
            "accountSeq": "12",
            "datasetId": "1111",
            "entity": {
                "addresses": [],
                "aliases": [{"alias": "DONNY JOHN", "type": "Alias"}],
                "citizenships": [],
                "createdDate": "12/09/2010",
                "dobs": [{"day": "11", "dob": "01/11/1924", "month": "01", "year": "1924"}],
                "entityType": "02",
                "id": "12321",
                "ids": [],
                "lastUpdateDate": "08/31/2010",
                "listCode": "EUS",
                "listId": "123",
                "name": "DOE DOE JOHN",
                "nationalities": [{"countryCode": "US", "nationality": "CHIC"}],
                "otherIds": [{"childId": "124134314"}],
                "pobs": [],
                "programs": [{"program": "UNITED STATES OF AMERICA", "type": "PPK"}],
                "sdfs": [
                    {"name": "EffectiveDate", "sdf": "09/01/2010"},
                    {"name": "Legal_Basis", "sdf": "2010/1209 (OJ L333)"},
                    {"name": "OriginalID", "sdf": "123143414"},
                ],
                "source": "EUS",
                "titles": [{"title": "PRESIDENT OF THE ACADEMY"}],
                "version": "32131312313213",
            },
            "entityId": "1232123",
            "entityTextType": "UPIDDDD",
            "entityType": "04",
            "entityVersion": "123123231213432423",
            "firstMatchedDate": "01/05/20",
            "inputVersionId": "213123124132431",
            "lastMatchedDate": "01/05/20",
            "lastReviewDate": "01/05/20",
            "masterId": "12312312432442524",
            "masterVersion": "asd123123343124141",
            "matchId": "2",
            "matchName": "secondMatchName",
            "matchStatus": "O",
            "matchType": "SSD",
            "riskScore": "-3.0",
            "sourceCode": "EUS",
            "stopDescriptors": [
                {
                    "name": "DOE DOE DOE",
                    "stopDescriptorDetails": [
                        {
                            "inputSynonym": "null",
                            "inputToken": "doe",
                            "matchScore": "2.0",
                            "sdToken": "john",
                        },
                        {
                            "inputSynonym": "syn",
                            "inputToken": "johnny",
                            "matchScore": "0.223",
                            "sdToken": "doe",
                        },
                    ],
                    "totalMatchScore": "0.22",
                },
                {
                    "name": "JOHN JOHN DOE DOE DOE",
                    "stopDescriptorDetails": [
                        {
                            "inputSynonym": "null",
                            "inputToken": "sude",
                            "matchScore": "0.25",
                            "sdToken": "zen",
                        },
                        {
                            "inputSynonym": "null",
                            "inputToken": "doe",
                            "matchScore": "3.0",
                            "sdToken": "doe",
                        },
                    ],
                    "totalMatchScore": "0.9999999999999",
                },
            ],
            "uniqueCustomerId": "R_RUS_Active_Address_2010-02-11-11.11",
        },
        {
            "accountSeq": "12",
            "datasetId": "1111",
            "entity": {
                "addresses": [],
                "aliases": [{"alias": "DONNY JOHN", "type": "Alias"}],
                "citizenships": [],
                "createdDate": "12/09/2010",
                "dobs": [{"day": "11", "dob": "01/11/1924", "month": "01", "year": "1924"}],
                "entityType": "02",
                "id": "12321",
                "ids": [],
                "lastUpdateDate": "08/31/2010",
                "listCode": "EUS",
                "listId": "123",
                "name": "DOE DOE JOHN",
                "nationalities": [{"countryCode": "US", "nationality": "CHIC"}],
                "otherIds": [{"childId": "124134314"}],
                "pobs": [],
                "programs": [{"program": "UNITED STATES OF AMERICA", "type": "PPK"}],
                "sdfs": [
                    {"name": "EffectiveDate", "sdf": "09/01/2010"},
                    {"name": "Legal_Basis", "sdf": "2010/1209 (OJ L333)"},
                    {"name": "OriginalID", "sdf": "123143414"},
                ],
                "source": "EUS",
                "titles": [{"title": "PRESIDENT OF THE ACADEMY"}],
                "version": "32131312313213",
            },
            "entityId": "1232123",
            "entityTextType": "UPIDDDD",
            "entityType": "04",
            "entityVersion": "123123231213432423",
            "firstMatchedDate": "01/05/20",
            "inputVersionId": "213123124132431",
            "lastMatchedDate": "01/05/20",
            "lastReviewDate": "01/05/20",
            "masterId": "12312312432442524",
            "masterVersion": "asd123123343124141",
            "matchId": "2",
            "matchName": "secondMatchName",
            "matchStatus": "O",
            "matchType": "SSD",
            "riskScore": "-3.0",
            "sourceCode": "EUS",
            "stopDescriptors": [
                {
                    "name": "DOE DOE DOE",
                    "stopDescriptorDetails": [
                        {
                            "inputSynonym": "null",
                            "inputToken": "doe",
                            "matchScore": "2.0",
                            "sdToken": "john",
                        },
                        {
                            "inputSynonym": "syn",
                            "inputToken": "johnny",
                            "matchScore": "0.223",
                            "sdToken": "doe",
                        },
                    ],
                    "totalMatchScore": "0.22",
                },
                {
                    "name": "JOHN JOHN DOE DOE DOE",
                    "stopDescriptorDetails": [
                        {
                            "inputSynonym": "null",
                            "inputToken": "sude",
                            "matchScore": "0.25",
                            "sdToken": "zen",
                        },
                        {
                            "inputSynonym": "null",
                            "inputToken": "doe",
                            "matchScore": "3.0",
                            "sdToken": "doe",
                        },
                    ],
                    "totalMatchScore": "0.9999999999999",
                },
            ],
            "uniqueCustomerId": "R_RUS_Active_Address_2010-02-11-11.11",
            "SRC_REF_KEY": "R_RUS_Active_Address_2010-02-11-11.11",
            "VERSION_ID": "213123124132431",
            "ENTITY_ID": "1232123",
            "ENTITY_VERSION": "123123231213432423",
            "WL_NAME": "DOE DOE JOHN",
            "WL_DOB": ["01/11/1924"],
            "WL_ENTITYTYPE": "04",
            "WL_NATIONALITY": ["CHIC"],
            "WL_CITIZENSHIP": [],
            "WL_POB": [],
            "WL_ALIASES": ["DONNY JOHN"],
            "WL_MATCHED_TOKENS": '["doe", "johnny", "sude", "doe"]',
            "WL_DOCUMENT_NUMBER": "",
        },
    )
]


EXAMPLE_FOR_TEST_SET_REF_KEY = {
    "entityTextType": "UPIDDDD",
    "AP_TRIGGERS": {"doe": {"ALL_PARTY_NAMES": ["John, Doe Doe"]}, "johnny": {}, "sude": {}},
    "TRIGGERED_BY": [
        "entityTextType",
        "SRC_REF_KEY",
        "masterVersion",
        "entity",
        "matchStatus",
        "sourceCode",
        "matchName",
        "matchType",
        "stopDescriptors",
        "uniqueCustomerId",
    ],
    "SRC_REF_KEY": "R_RUS_Active_Address_2010-02-11-11.11",
    "masterVersion": "asd123123343124141",
    "entity": {
        "addresses": [],
        "aliases": [{"alias": "DONNY JOHN", "type": "Alias"}],
        "citizenships": [],
        "createdDate": "12/09/2010",
        "dobs": [{"day": "11", "dob": "01/11/1924", "month": "01", "year": "1924"}],
        "entityType": "02",
        "id": "12321",
        "ids": [],
        "lastUpdateDate": "08/31/2010",
        "listCode": "EUS",
        "listId": "123",
        "name": "DOE DOE JOHN",
        "nationalities": [{"countryCode": "US", "nationality": "CHIC"}],
        "otherIds": [{"childId": "124134314"}],
        "pobs": [],
        "programs": [{"program": "UNITED STATES OF AMERICA", "type": "PPK"}],
        "sdfs": [
            {"name": "EffectiveDate", "sdf": "09/01/2010"},
            {"name": "Legal_Basis", "sdf": "2010/1209 (OJ L333)"},
            {"name": "OriginalID", "sdf": "123143414"},
        ],
        "source": "EUS",
        "titles": [{"title": "PRESIDENT OF THE ACADEMY"}],
        "version": "32131312313213",
    },
    "WL_MATCHED_TOKENS": '["doe", "johnny", "sude", "doe"]',
}


RESULT_FOR_EXAMPLE_FOR_TEST_SET_REF_KEY = [
    "entityTextType",
    "AP_TRIGGERS",
    "TRIGGERED_BY",
    "SRC_REF_KEY",
    "masterVersion",
    "entity",
]


EXAMPLE_PARTIES = [
    {
        "accountBU": "US_WM",
        "countryOfIncorporation": "Arabian Emirates",
        "id": "1231231231236",
        "partyCountryOfBirth": "1341412312312",
        "partyId": "1324134123123",
        "partyName": "Shaolin kung fu master",
        "taxId": "1231413412312",
        "taxIdType": "AUS",
    },
    {
        "accountBU": "US_VM_SS",
        "dobDate": "10/10/1969",
        "id": "43134134123123",
        "partyCountryOfBirth": "13413401280",
        "partyId": "31231241234124",
        "partyName": "John, Doe Doe",
        "partyPrimaryCitizenshipCountry": "Arabian Emirates",
        "taxId": "12097381208937",
        "taxIdType": "SSH",
    },
]

EXAMPLE_PARTIES_WITH_NAMES = [
    {
        "accountBU": "US_WM",
        "countryOfIncorporation": "Arabian Emirates",
        "id": "1231231231236",
        "partyCountryOfBirth": "1341412312312",
        "partyId": "1324134123123",
        "partyName": "Shaolin kung fu master",
        "taxId": "1231413412312",
        "taxIdType": "AUS",
        "PRTY_FST_NM": "Ultra",
        "PRTY_MDL_NM": "Giga",
        "PRTY_LST_NM": "Pole",
    },
    {
        "accountBU": "US_VM_SS",
        "dobDate": "10/10/1969",
        "id": "43134134123123",
        "partyCountryOfBirth": "13413401280",
        "partyId": "31231241234124",
        "partyName": "John, Doe Doe",
        "partyPrimaryCitizenshipCountry": "Arabian Emirates",
        "taxId": "12097381208937",
        "taxIdType": "SSH",
    },
]
