@Library('pipeline-shared-library') _

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: true,
    failPipeline: true,
    dependencyCheckEnabled: true,
    includeBuildNumberInSnapshotVersion: true,
    archiveArtifactsPattern: '**/build/libs/*-exec.jar'
)
