package com.silenteight.bridge.core.recommendation.domain.model;

public enum RecommendedAction {
  ACTION_INVESTIGATE,
  ACTION_INVESTIGATE_HINTED_FALSE_POSITIVE,
  ACTION_INVESTIGATE_PARTIALLY_FALSE_POSITIVE,
  ACTION_INVESTIGATE_HINTED_TRUE_POSITIVE,
  ACTION_FALSE_POSITIVE,
  ACTION_POTENTIAL_TRUE_POSITIVE
}
