@Library('pipeline-shared-library@github') _

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: true,
    failPipeline: true,
    sonarDecorate: true,
    dependencyCheckEnabled: true,
    archiveArtifactsPattern: '**/build/libs/*.jar')
