@Library('pipeline-shared-library@master') _

def gradle = new com.silenteight.jenkins.ci.Gradle()
def git = new com.silenteight.jenkins.ci.Git()
def jenkins = new com.silenteight.jenkins.ci.Jenkins()

gradleBuild(
    jdkVersion: 'jdk-17',
    sonarEnabled: false,
    failPipeline: true,
    sonarDecorate: true,
    dependencyCheckEnabled: true,
    includeBuildNumberInSnapshotVersion: true,

    additionalStages: {
        deployOnNomad()
    }
)
