@Library('pipeline-shared-library@master') _

def gradle = new com.silenteight.jenkins.ci.Gradle()
def git = new com.silenteight.jenkins.ci.Git()
def jenkins = new com.silenteight.jenkins.ci.Jenkins()

gradleBuild(
    jdkVersion: 'jdk-17',
    sonarEnabled: false,
    failPipeline: true,
    sonarDecorate: true,
    dependencyCheckEnabled: true,
    includeBuildNumberInSnapshotVersion: true,

    additionalParams: [
      extendedChoice(
        name: 'environments',
        value: 'dev,lima,test',
        defaultValue: 'lima',
        description: 'Environments to deploy to on Nomad',
        multiSelectDelimiter: ',',
        quoteValue: false,
        saveJSONParameterToFile: false,
        type: 'PT_MULTI_SELECT',
        visibleItemCount: 10
        )
      ],
    additionalStages: {
        //buildContainerImage()
        //awsECR()
        //helmChartRegistry()
        deployOnNomad()
    }
)
