export enum Solution {
  FALSE_POSITIVE = 'FALSE_POSITIVE',
  POTENTIAL_TRUE_POSITIVE = 'POTENTIAL_TRUE_POSITIVE',
  HINTED_FALSE_POSITIVE = 'HINTED_FALSE_POSITIVE',
  HINTED_POTENTIAL_TRUE_POSITIVE = 'HINTED_POTENTIAL_TRUE_POSITIVE',
  NO_DECISION = 'NO_DECISION'
}
