# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import temp_agent.hit_type_agent_pb2 as hit__type__agent__pb2


class HitTypeAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckTriggers = channel.unary_unary(
            "/silenteight.agent.hittype.v1.api.HitTypeAgent/CheckTriggers",
            request_serializer=hit__type__agent__pb2.CheckTriggersRequest.SerializeToString,
            response_deserializer=hit__type__agent__pb2.CheckTriggersResponse.FromString,
        )


class HitTypeAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckTriggers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HitTypeAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CheckTriggers": grpc.unary_unary_rpc_method_handler(
            servicer.CheckTriggers,
            request_deserializer=hit__type__agent__pb2.CheckTriggersRequest.FromString,
            response_serializer=hit__type__agent__pb2.CheckTriggersResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "silenteight.agent.hittype.v1.api.HitTypeAgent", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class HitTypeAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckTriggers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/silenteight.agent.hittype.v1.api.HitTypeAgent/CheckTriggers",
            hit__type__agent__pb2.CheckTriggersRequest.SerializeToString,
            hit__type__agent__pb2.CheckTriggersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
