import { Component, OnInit, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';

const ELEMENT_DATA = [
  {
    alertId: 'AE_BTCH_PEPL!7D9AA654-22EA231A-CF15BFE7-320439BB',
    aiComment: 'AZ07300094: The hit was generated by NATIONAL_ID.\'Alerted Party\'s name.',
    aiCommentDate: '2019-12-05 13:45:29',
    analystComment: 'FCSU analyst text clearly listing the disagreed hits\'in',
    analystCommentDate: '2019-12-05 13:45:29'
  },
  {
    alertId: 'AE_BTCH_PEPL!7D9AA654-22EA231A-CF15BFE7-320439BB',
    aiComment: 'AZ07300094: The hit was generated by NATIONAL_ID.\'Alerted Party\'s name.',
    aiCommentDate: '2019-12-05 13:45:29',
    analystComment: 'FCSU analyst text clearly listing the disagreed hits\'in',
    analystCommentDate: '2019-12-05 13:45:29'
  }
];

@Component({
  selector: 'app-circuit-breaker-alerts-table',
  templateUrl: './circuit-breaker-alerts-table.component.html'
})
export class CircuitBreakerAlertsTableComponent implements OnInit {

  displayedColumns: string[] = [
    'alertId',
    'aiComment',
    'aiCommentDate',
    'analystComment',
    'analystCommentDate'
  ];
  dataSource = new MatTableDataSource(ELEMENT_DATA);

  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;

  translatePrefix = 'circuitBreakerDashboard.element.dataLabels.';

  constructor() { }

  ngOnInit() {
    this.dataSource.paginator = this.paginator;
  }

}
