@Library('pipeline-shared-library@master') _

def gradle = new com.silenteight.jenkins.ci.Gradle()
def git = new com.silenteight.jenkins.ci.Git()
def jenkins = new com.silenteight.jenkins.ci.Jenkins()

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: true,
    dependencyCheckEnabled: true,
    includeBuildNumberInSnapshotVersion: true,
    additionalParams: [
      extendedChoice(
            name: 'environments',
            value: 'dev,lima,test,mike,foxtrot',
            defaultValue: '',
            description: 'Environments to deploy to on Nomad',
            multiSelectDelimiter: ',',
            quoteValue: false,
            saveJSONParameterToFile: false,
            type: 'PT_MULTI_SELECT',
            visibleItemCount: 10
            ),
      ],
    additionalStages: {
      stage('Build and deploy container image') {
        script {
          dir( './scripts' ) {
            stash includes: '**', name: 'scripts'
          }
          dir( './helm-chart' ) {
            stash includes: '**', name: 'helm'
          }
          if (git.getGitBranch() == 'master' || git.buildingReleaseBranch()) {
            gradle.gradle('jib')
          } else {
            echo 'This is not a release branch ignore docker image deployment'
          }
        }
      }

      stage('Helm Chart registry') {
        env.INSTALLER_VERSION = gradle.getGradleProjectVersion()
        echo 'Helm Chart building....'
        node("aws-worker") {
          // Stash is done in first stage
          dir( './scripts' ) {
            unstash 'scripts'
          }
          dir( './helm-chart' ) {
            unstash 'helm'
          }
          script {
            if (git.getGitBranch() == 'master' || git.buildingReleaseBranch()) {
              echo 'Helm Chart version'
              sh './scripts/helm-chart-build.sh'
            } else {
              echo 'This is not a master release or hotfix branch. Ignoring Helm Chart deployment.'
            }
          }
        }
      }

      stage('AWS ECR') {
        //This is docker image tag version which will be used to copy from s8 repository
        env.INSTALLER_VERSION = gradle.getGradleProjectVersion()
        node("aws-worker") {
          // Stash is done in first stage
          dir( './scripts' ) {
            unstash 'scripts'
          }
          dir( './helm-chart' ) {
            unstash 'helm'
          }
          script {
            if (git.getGitBranch() == 'master' || git.buildingReleaseBranch()) {
              echo 'AWS image push'
              sh './scripts/aws-deploy.sh'
            } else {
              echo 'This is not a master release or hotfix branch. Ignoring AWS ECR push.'
            }
          }
        }
      }
      deployOnNomad()
    }
)
