@Library('pipeline-shared-library') _

gradleBuild(
  jdkVersion: 'jdk-11',
  sonarEnabled: true,
  dependencyCheckEnabled: true,
  includeBuildNumberInSnapshotVersion: true,
  archiveArtifactsPattern: '**/build/libs/*-exec.jar',
  additionalParams: [
    extendedChoice(
      name: 'environments',
      value: 'dev,test,mike,lima,foxtrot',
      defaultValue: 'foxtrot',
      description: 'Environments to deploy to on Nomad',
      multiSelectDelimiter: ',',
      quoteValue: false,
      saveJSONParameterToFile: false,
      type: 'PT_MULTI_SELECT',
      visibleItemCount: 10
      ),
    booleanParam(
      name: 'forceDeploy',
      defaultValue: false,
      description: 'Deploy from other branches then master'
    )
  ],
  additionalStages: {
    buildContainerImage()
    deployOnNomad()
  }
)
