@Library('pipeline-shared-library') _

gradleBuild(
    jdkVersion: 'jdk-11',
    sonarEnabled: true,
    failPipeline: true,
    dependencyCheckEnabled: true,
    archiveArtifactsPattern: '**/build/libs/*.jar, plugins/**/*.jar',
    includeBuildNumberInSnapshotVersion: true
)
