@startuml
header Approver flow

actor Approver

box "WebApp Frontend" #MintCream
    participant Frontend as "Approver Queue GUI"
end box

box "WebApp Backend" #LightGreen
    participant Backend as "WebApp"
    database WebAppDB as "WebApp Database"
end box

box "Governance" #LightBlue
    participant Governance as "Governance" order 45
end box

box "RabbitMQ"
    queue Queue order 50
end box

Frontend ->> Backend : Fetch Change Requests

activate Backend
Backend <-> WebAppDB : Fetch pending Change Requests
note over Backend, WebAppDB
    * Change Request Id
    * Bulk Change Id
    * Username
    * Comment
    * Attachments URLs
    * Creation At
end note
Backend -->> Frontend : Change Requests list
deactivate Backend


Frontend ->> Backend : Fetch Bulk Changes
activate Backend
Backend <-> Governance : Fetch pending Bulk Changes
note over Backend, Governance
    * Bulk Change Id
    * List of RB Ids
    * AI Solution (possible 'no change')
    * Status (possible 'no change')
end note

Backend -->> Frontend : Bulk Change list
deactivate Backend

Frontend -->> Frontend : Merge Bulk Change List and ChangeRequest List
note over Frontend
    If we are not able to fetch BulkChange details
    we should hide the apply/reject button.
end note

Frontend -->> Approver : Present list of Pending Change Requests


==  Approve Change Request  ==

Approver -> Frontend : Click "Approve"
Frontend ->> Backend : Change Request Approve request

Backend -> Queue : Send ChangeRequest Approve Command
note over Backend, Queue
    * ChangeRequest Id
    * Approver Username
    * Approved At
end note

Backend -->> Frontend : Approval success result

Frontend -->> Approver : Inform about success


==  Reject Change Request  ==

Approver -> Frontend : Click "Reject"
Frontend ->> Backend : Change Request reject request

Backend -> Queue : Send ChangeRequest Reject Command
note over Backend, Queue
    * ChangeRequest Id
    * Approver Username
    * Rejected At
end note

Backend -->> Frontend : Approval reject result

Frontend -->> Approver : Inform about success

@enduml
