@startuml
header Get Reasoning Branch Details

actor BO as "Business Operator"

box "WebApp Frontend" #MintCream
    participant Frontend as "RB Browser"
end box

box "WebApp Backend" #LightGreen
    participant Backend as "WebApp"
end box

box "Governance" #LightBlue
    participant G as "Governance"
end box

BO -> Frontend : Select Reasoning Branch

activate Frontend
Frontend -> Backend : Fetch Reasoning Branch Feature Values
note over Frontend, Backend
    * Reasoning Branch ID (DT ID + FV ID)
end note

activate Backend
Backend <-> G : Fetch Reasoning Branch Feature Values
note over Backend, G
    * Feature Value
end note

Backend -> Frontend : Reasoning Branch Feature Values
deactivate Backend

Frontend -> Backend : Fetch Feature Names
activate Backend
note over Frontend, Backend
    * Feature Vector ID
end note

Backend <-> G : Fetch Feature Names
note over Backend, G
    * Feature Name
end note

Backend -> Frontend : Feature Names
deactivate Backend

Frontend -> BO: Reasoning Branch Details
deactivate Frontend
note over Frontend, BO
    * Reasoning Branch ID
    * Solution
    * Status
    * Last update
    * Features
end note

@enduml
