@startuml
header List discrepant branches

actor "Business Operator"

box "WebApp Frontend" #MintCream
    participant Frontend as "CB Dashboard GUI"
end box

box "WebApp Backend" #LightGreen
    participant Backend as "WebApp"
end box

box "Circuit Breaker" #LightBlue
    participant CB as "Circuit Breaker" order 48
end box

"Business Operator" -> Frontend : Select CB Dashboard

Frontend -> Backend : Fetch Discrepant Branches
activate Backend
Backend <-> CB : Fetch Discrepant Branches
note over Backend, CB
    * RB ID
    * Date when the RB was disabled
end note

Backend -> Frontend : Discrepant Branches list
deactivate Backend
Frontend->"Business Operator": Discrepant Branches list

"Business Operator" -> Frontend : Click on a Discrepant Branch
Frontend -> Backend : Get Discrepancy IDs by Discrepant Branch ID
activate Backend
Backend <-> CB : Fetch Discrepancy IDs by Discrepant Branch ID
Backend -> Frontend : Discrepancy IDs
deactivate Backend

Frontend ->> Frontend : Select a subset of Discrepancy IDs representing the 1st page

Frontend -> Backend : Get page of Discrepancies by Discrepancy IDs
activate Backend
Backend <-> CB : Get Discrepancies by Ids
note over Backend, CB
    * Alert ID
    * AI Comment
    * AI Comment Date
    * Analyst Comment
    * Analyst Comment Date
end note
Backend -> Frontend : Discrepancy list
deactivate Backend
Frontend->"Business Operator": First page of Discrepancy list

"Business Operator" -> Frontend : Click to display another page of Discrepancies
Frontend ->> Frontend : Select a subset of Discrepancy IDs representing the selected page

Frontend -> Backend : Get another page of Discrepancies by Discrepancy IDs
activate Backend
Backend <-> CB : Get Discrepancies by Ids

Backend -> Frontend : Discrepancy list
deactivate Backend
Frontend->"Business Operator": Another page of Discrepancy list


@enduml
