@startuml
header Business Operator flow

actor BusinessOperator

box "WebApp Frontend" #MintCream
    participant Frontend as "Business Operator Queue GUI"
end box

box "WebApp Backend" #LightGreen
    participant Backend as "WebApp"
    database WebAppDB as "WebApp Database"
end box

box "Governance" #LightBlue
    participant Governance as "Governance" order 45
end box

box "RabbitMQ"
    queue Queue order 50
end box

Frontend -->> BusinessOperator : Present list of Pending Change Requests

==  Cancel Change Request  ==

BusinessOperator -> Frontend : Click "Cancel"
Frontend ->> Backend : Change Request Cancel request

Backend -> Queue : Send ChangeRequest Cancel Command
note over Backend, Queue
    * ChangeRequest Id
    * Business Operator Username
    * Cancelled At
end note

Backend -->> Frontend : Cancellation success result

Frontend -->> BusinessOperator : Inform about success

@enduml
