@startuml
header Maker flow

box "WebApp Backend"
    participant Backend as "WebApp" order 20
    database WebAppDB as "WebApp Database" order 30
end box

box "RabbitMQ"
    queue Queue order 10
end box

Queue -> Backend : ChangeRequest Reject Command

note over Queue, Backend
    * Bulk Change Id
    * Username
    * Creation At
end note

activate Backend

Backend -> WebAppDB : Update ChangeRequest

note over Backend, WebAppDB
    * Status = Rejected
    * Approver Username
end note

Backend -> Queue : Bulk Change Reject Command
note over Queue, Backend
    * Bulk Change Id
end note


deactivate Backend

@enduml
