@startuml
header Maker flow

box "WebApp Backend"
    participant Backend as "WebApp" order 20
    database WebAppDB as "WebApp Database" order 30
end box

box "RabbitMQ"
    queue Queue order 10
end box

Queue -> Backend : ChangeRequest Approve Command

note over Queue, Backend
    * Change Request Id
    * Username
    * Approve At
end note

activate Backend

Backend -> WebAppDB : Update ChangeRequest

note over Backend, WebAppDB
    * Status = Approved
    * Decided By
    * Decided At
end note

Backend <-> WebAppDB : Fetch Bulk Change Id

Backend -> Queue : Bulk Change Apply Command
note over Queue, Backend
    * Bulk Change Id
end note


deactivate Backend

@enduml
