@startuml
header Maker flow

box "RabbitMQ"
    queue Queue order 10
end box

box "WebApp Backend"
    participant Backend as "WebApp" order 20
    database WebAppDB as "WebApp Database" order 30
end box

activate Backend

Queue -> Backend : ChangeRequest Command
    note over Queue, Backend
        * Bulk Change Id (UUID)
        * Username
        * Comment
        * Attachments Urls
        * Creation At
    end note

Backend -> WebAppDB : Persist new Change Request
    note over Backend, WebAppDB
        * Bulk Change Id (UUID)
        * Created By
        * Created At
        * Comment
        * Attachments Urls
    end note

deactivate Backend

@enduml
