package com.silenteight.hsbc.bridge.model.dto;

public enum ModelType {
  MODEL,
  IS_PEP_PROCEDURAL,
  IS_PEP_HISTORICAL,
  NAME_ALIASES,
  HISTORICAL_DECISIONS_ALERTED_PARTY,
  HISTORICAL_DECISIONS_WATCHLIST_PARTY,
  HISTORICAL_DECISIONS_MATCH,
}
