= The CBS Integration Alert Queuing

.Queuing CBS alerts for fetching data
[plantuml,queuing-alerts-diagram,svg]
....
@startuml
database "Oracle" as Oracle
participant "QueuingJob" as QueuingJob
database "Postgres" as Postgres
participant "FetchingJob" as FetchingJob
participant "Feeding" as Feeding
participant "RecommendationService" as Recommendations
queue "RabbitMQ" as RabbitMQ
participant "Core Bridge" as CoreBridge


== **1) Get Alerts for Processing** ==
autonumber
QueuingJob -> Oracle : Fetch SYSTEM_ID, BATCH_ID
activate QueuingJob
Oracle --> QueuingJob : Return SYSTEM_ID, BATCH_ID
QueuingJob -> Postgres : Store unique alertIds
deactivate QueuingJob
activate Postgres

== **2) Fetching Alerts** ==

FetchingJob -> Postgres : Read AlertIds by priority
activate FetchingJob
Postgres --> FetchingJob : Return AlertIds

FetchingJob -> Postgres : Store batch info
FetchingJob -> Oracle : Fetch full alerts with details
Oracle --> FetchingJob : Return full alerts with details
FetchingJob -> FetchingJob : Parsing alerts
FetchingJob -> Postgres : Store raw alerts
FetchingJob -> CoreBridge : gRPC - Register alerts
activate CoreBridge
CoreBridge --> FetchingJob : Return alert and matches names
deactivate CoreBridge
FetchingJob -> Feeding : Feed UDS
FetchingJob -> Oracle : Acknowledge alerts
FetchingJob -> Postgres : Update status of alert
deactivate FetchingJob
deactivate Postgres

== **3) Submitting Recommendations** ==

RabbitMQ -> Recommendations : Recommendations generated
activate Recommendations
Recommendations -> CoreBridge : gRPC - Get recommendations
activate CoreBridge
CoreBridge --> Recommendations : Return recommendations
deactivate CoreBridge
Recommendations -> Postgres : Store recommendation
activate Postgres
Recommendations -> Oracle : Send recommendation if Watchlist-level
Oracle --> Recommendations : Return status code
Recommendations -> Postgres : Update recommendation with recom status
deactivate Postgres
deactivate Recommendations
@enduml
....

Process of solving alerts from CBS can be divided into 3 steps:

. Getting alerts for processing
+
Purpose of this step is to constantly monitor CBS views for the existence of new alerts to solve. CBS can have multiple views feeding alerts to solve and they should be read as soon as they appear in the view. When alert is ingested into the system it will have an assigned priority with which it should be processed further by the system.
. Fetching alerts with corresponding data
+
Purpose of this step is to read all alert data, call ACK function and send alert for further processing.
. Submitting recommendation
+
In this step, recommendation generated at watchlist-level is sent back to CBS using call to RECOM function. All recommendations are also stored in postgres database.
