package com.silenteight.sens.webapp.backend.report.scb;

import com.silenteight.sens.webapp.backend.report.Report;
import com.silenteight.sens.webapp.common.testing.time.MockTimeSource;

import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.assertj.core.api.Assertions.*;

class EntitlementReportGeneratorTest {

  private EntitlementReportGenerator underTest = new EntitlementReportGenerator(
      new MockTimeSource(Instant.parse("2011-12-03T10:15:30Z")),
      new ScbReportDateFormatter());

  @Test
  void generateEntitlementReportWhenRequested() {
    Report report = underTest.generateReport();

    assertThat(report.getReportFileName()).isEqualTo("entitlement-report.csv");
    assertThat(report.getReportContent().lines()).containsExactly(getExpectedReport());
  }

  @NotNull
  private static String[] getExpectedReport() {
    return new String[] {
        "Application Name,Surveillance Optimization,,",
        "Report Generated By,System,,",
        "Run Date,20111203101530,,",
        "Number of data records,9,,",
        "Entitlement Name,Entitlement Type,Entitlement Description,Entitlement Link",
        "ROLE_AUDITOR,USER,A user that can generate and download reports from UI",
        "ROLE_INBOX_OPERATOR,USER,A user that can see a list of inbox messages,",
        "ROLE_USER_MANAGER,USER,A user that can manage users,",
        "ROLE_ANALYST,USER,A user that can use a SENS Chrome Extension,",
        "ROLE_BATCH_TYPE_MANAGER,USER,A user that can manage an assigned and "
            + "an activated batch types,",
        "ROLE_DECISION_TREE_MANAGER,USER,A user that can manage decision trees,",
        "ROLE_MAKER,USER,A user that can submit changes to reasoning branches,",
        "ROLE_APPROVER,USER,A user that can approve changes in reasoning branches,",
        "SUPERUSER,ADMIN,A user that have all roles mentioned above,"};
  }
}
