# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import company_name_surrounding.company_name_surrounding_agent_pb2 as company__name__surrounding__agent__pb2


class CompanyNameSurroundingAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckCompanyNameSurrounding = channel.unary_unary(
                '/silenteight.agent.companynamesurrounding.v1.api.CompanyNameSurroundingAgent/CheckCompanyNameSurrounding',
                request_serializer=company__name__surrounding__agent__pb2.CheckCompanyNameSurroundingRequest.SerializeToString,
                response_deserializer=company__name__surrounding__agent__pb2.CheckCompanyNameSurroundingResponse.FromString,
                )


class CompanyNameSurroundingAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckCompanyNameSurrounding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanyNameSurroundingAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckCompanyNameSurrounding': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCompanyNameSurrounding,
                    request_deserializer=company__name__surrounding__agent__pb2.CheckCompanyNameSurroundingRequest.FromString,
                    response_serializer=company__name__surrounding__agent__pb2.CheckCompanyNameSurroundingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'silenteight.agent.companynamesurrounding.v1.api.CompanyNameSurroundingAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CompanyNameSurroundingAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckCompanyNameSurrounding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/silenteight.agent.companynamesurrounding.v1.api.CompanyNameSurroundingAgent/CheckCompanyNameSurrounding',
            company__name__surrounding__agent__pb2.CheckCompanyNameSurroundingRequest.SerializeToString,
            company__name__surrounding__agent__pb2.CheckCompanyNameSurroundingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
