@Library('pipeline-shared-library@master') _

def gradle = new com.silenteight.jenkins.ci.Gradle()
def git = new com.silenteight.jenkins.ci.Git()
def jenkins = new com.silenteight.jenkins.ci.Jenkins()

gradleBuild(
    jdkVersion: 'jdk-17',
    sonarEnabled: true,
    failPipeline: true,
    sonarDecorate: true,
    dependencyCheckEnabled: true,
    includeBuildNumberInSnapshotVersion: true,
    archiveArtifactsPattern: '**/build/libs/*.jar, plugins/**/*.jar',
    additionalParams: [
      extendedChoice(
        name: 'environments',
        value: 'dev,test,mike',
        defaultValue: 'mike',
        description: 'Environments to deploy to on Nomad',
        multiSelectDelimiter: ',',
        quoteValue: false,
        saveJSONParameterToFile: false,
        type: 'PT_MULTI_SELECT',
        visibleItemCount: 10
        )
    ],

    additionalStages: {
      deployOnNomad()
    }
)
