@Library('pipeline-shared-library') _
def utils = new com.silenteight.jenkins.ci.Utils()
def jenkins = new com.silenteight.jenkins.ci.Jenkins()

pipeline {
    agent none
    environment {
        PYPI_URL = credentials('pypi-readonly-url')
    }

    stages {
        stage('Prepare python image') {
            agent any
            steps {
                sh 'docker pull python:3.7'
            }
        }
        stage('Prepare') {
            agent {
                docker {
                    image 'python:3.7'
                }
            }
            stages {
                stage('Build') {
                    steps {
                        sh './scripts/clean.sh'
                        sh './scripts/bootstrap.sh --index-url $PYPI_URL'
                        sh './scripts/build.sh --index-url $PYPI_URL'
                    }
                }
                stage('Test') {
                    steps {
                        sh './scripts/test.sh --index-url $PYPI_URL'
                    }
                }
            }
            post {
                always {
                    junit '.tox/*.xml'
                    archiveArtifacts artifacts: 'dist/*', fingerprint: true
                }
                success {
                    stash includes: 'dist/*', name: 'artifacts'
                }
            }
        }

        stage('Nomad'){
            agent {
                label 'nomad'
            }
            stages {
                stage('Prepare nomad artifacts') {
                    steps {
                        unstash 'artifacts'
                        sh './nomad/prepare.sh'
                    }
                }
                stage('Deploy on nomad dev') {
                    steps {
                        script {
                            if (utils.getGitBranch() == 'master') {
                                sh './nomad/full/deploy.sh'
                            } else {
                                echo 'This is not a release branch'
                            }
                        }
                    }
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'nomad/*.tar.bz2', fingerprint: true
                }
            }
       }
    }
}

