package com.silenteight.payments.bridge.ae.domain.recommendation.port;

import com.silenteight.adjudication.api.v2.RecommendationWithMetadata;

/**
 * The listener that receives recommendation generated by Adjudication Engine.
 */
public interface RecommendationListener {

  void alertRecommended(RecommendationWithMetadata recommendationWithMetadata);
}
